// Code generated by ent, DO NOT EDIT.

package billingprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the billingprofile type in the database.
	Label = "billing_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldBalanceRateMultiplier holds the string denoting the balance_rate_multiplier field in the database.
	FieldBalanceRateMultiplier = "balance_rate_multiplier"
	// FieldPeakRateEnabled holds the string denoting the peak_rate_enabled field in the database.
	FieldPeakRateEnabled = "peak_rate_enabled"
	// FieldPeakStart holds the string denoting the peak_start field in the database.
	FieldPeakStart = "peak_start"
	// FieldPeakEnd holds the string denoting the peak_end field in the database.
	FieldPeakEnd = "peak_end"
	// FieldPeakRateMultiplier holds the string denoting the peak_rate_multiplier field in the database.
	FieldPeakRateMultiplier = "peak_rate_multiplier"
	// FieldImageRateIndependent holds the string denoting the image_rate_independent field in the database.
	FieldImageRateIndependent = "image_rate_independent"
	// FieldImageRateMultiplier holds the string denoting the image_rate_multiplier field in the database.
	FieldImageRateMultiplier = "image_rate_multiplier"
	// FieldImagePrice1k holds the string denoting the image_price_1k field in the database.
	FieldImagePrice1k = "image_price_1k"
	// FieldImagePrice2k holds the string denoting the image_price_2k field in the database.
	FieldImagePrice2k = "image_price_2k"
	// FieldImagePrice4k holds the string denoting the image_price_4k field in the database.
	FieldImagePrice4k = "image_price_4k"
	// FieldBatchImageDiscountMultiplier holds the string denoting the batch_image_discount_multiplier field in the database.
	FieldBatchImageDiscountMultiplier = "batch_image_discount_multiplier"
	// FieldBatchImageHoldMultiplier holds the string denoting the batch_image_hold_multiplier field in the database.
	FieldBatchImageHoldMultiplier = "batch_image_hold_multiplier"
	// FieldVideoRateIndependent holds the string denoting the video_rate_independent field in the database.
	FieldVideoRateIndependent = "video_rate_independent"
	// FieldVideoRateMultiplier holds the string denoting the video_rate_multiplier field in the database.
	FieldVideoRateMultiplier = "video_rate_multiplier"
	// FieldVideoPrice480p holds the string denoting the video_price_480p field in the database.
	FieldVideoPrice480p = "video_price_480p"
	// FieldVideoPrice720p holds the string denoting the video_price_720p field in the database.
	FieldVideoPrice720p = "video_price_720p"
	// FieldVideoPrice1080p holds the string denoting the video_price_1080p field in the database.
	FieldVideoPrice1080p = "video_price_1080p"
	// FieldWebSearchPricePerCall holds the string denoting the web_search_price_per_call field in the database.
	FieldWebSearchPricePerCall = "web_search_price_per_call"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the billingprofile in the database.
	Table = "billing_profiles"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "billing_profiles"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for billingprofile fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGroupID,
	FieldBalanceRateMultiplier,
	FieldPeakRateEnabled,
	FieldPeakStart,
	FieldPeakEnd,
	FieldPeakRateMultiplier,
	FieldImageRateIndependent,
	FieldImageRateMultiplier,
	FieldImagePrice1k,
	FieldImagePrice2k,
	FieldImagePrice4k,
	FieldBatchImageDiscountMultiplier,
	FieldBatchImageHoldMultiplier,
	FieldVideoRateIndependent,
	FieldVideoRateMultiplier,
	FieldVideoPrice480p,
	FieldVideoPrice720p,
	FieldVideoPrice1080p,
	FieldWebSearchPricePerCall,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultBalanceRateMultiplier holds the default value on creation for the "balance_rate_multiplier" field.
	DefaultBalanceRateMultiplier float64
	// DefaultPeakRateEnabled holds the default value on creation for the "peak_rate_enabled" field.
	DefaultPeakRateEnabled bool
	// DefaultPeakStart holds the default value on creation for the "peak_start" field.
	DefaultPeakStart string
	// PeakStartValidator is a validator for the "peak_start" field. It is called by the builders before save.
	PeakStartValidator func(string) error
	// DefaultPeakEnd holds the default value on creation for the "peak_end" field.
	DefaultPeakEnd string
	// PeakEndValidator is a validator for the "peak_end" field. It is called by the builders before save.
	PeakEndValidator func(string) error
	// DefaultPeakRateMultiplier holds the default value on creation for the "peak_rate_multiplier" field.
	DefaultPeakRateMultiplier float64
	// DefaultImageRateIndependent holds the default value on creation for the "image_rate_independent" field.
	DefaultImageRateIndependent bool
	// DefaultImageRateMultiplier holds the default value on creation for the "image_rate_multiplier" field.
	DefaultImageRateMultiplier float64
	// DefaultBatchImageDiscountMultiplier holds the default value on creation for the "batch_image_discount_multiplier" field.
	DefaultBatchImageDiscountMultiplier float64
	// DefaultBatchImageHoldMultiplier holds the default value on creation for the "batch_image_hold_multiplier" field.
	DefaultBatchImageHoldMultiplier float64
	// DefaultVideoRateIndependent holds the default value on creation for the "video_rate_independent" field.
	DefaultVideoRateIndependent bool
	// DefaultVideoRateMultiplier holds the default value on creation for the "video_rate_multiplier" field.
	DefaultVideoRateMultiplier float64
)

// OrderOption defines the ordering options for the BillingProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByBalanceRateMultiplier orders the results by the balance_rate_multiplier field.
func ByBalanceRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceRateMultiplier, opts...).ToFunc()
}

// ByPeakRateEnabled orders the results by the peak_rate_enabled field.
func ByPeakRateEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakRateEnabled, opts...).ToFunc()
}

// ByPeakStart orders the results by the peak_start field.
func ByPeakStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakStart, opts...).ToFunc()
}

// ByPeakEnd orders the results by the peak_end field.
func ByPeakEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakEnd, opts...).ToFunc()
}

// ByPeakRateMultiplier orders the results by the peak_rate_multiplier field.
func ByPeakRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakRateMultiplier, opts...).ToFunc()
}

// ByImageRateIndependent orders the results by the image_rate_independent field.
func ByImageRateIndependent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageRateIndependent, opts...).ToFunc()
}

// ByImageRateMultiplier orders the results by the image_rate_multiplier field.
func ByImageRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageRateMultiplier, opts...).ToFunc()
}

// ByImagePrice1k orders the results by the image_price_1k field.
func ByImagePrice1k(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImagePrice1k, opts...).ToFunc()
}

// ByImagePrice2k orders the results by the image_price_2k field.
func ByImagePrice2k(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImagePrice2k, opts...).ToFunc()
}

// ByImagePrice4k orders the results by the image_price_4k field.
func ByImagePrice4k(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImagePrice4k, opts...).ToFunc()
}

// ByBatchImageDiscountMultiplier orders the results by the batch_image_discount_multiplier field.
func ByBatchImageDiscountMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchImageDiscountMultiplier, opts...).ToFunc()
}

// ByBatchImageHoldMultiplier orders the results by the batch_image_hold_multiplier field.
func ByBatchImageHoldMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchImageHoldMultiplier, opts...).ToFunc()
}

// ByVideoRateIndependent orders the results by the video_rate_independent field.
func ByVideoRateIndependent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoRateIndependent, opts...).ToFunc()
}

// ByVideoRateMultiplier orders the results by the video_rate_multiplier field.
func ByVideoRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoRateMultiplier, opts...).ToFunc()
}

// ByVideoPrice480p orders the results by the video_price_480p field.
func ByVideoPrice480p(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoPrice480p, opts...).ToFunc()
}

// ByVideoPrice720p orders the results by the video_price_720p field.
func ByVideoPrice720p(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoPrice720p, opts...).ToFunc()
}

// ByVideoPrice1080p orders the results by the video_price_1080p field.
func ByVideoPrice1080p(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoPrice1080p, opts...).ToFunc()
}

// ByWebSearchPricePerCall orders the results by the web_search_price_per_call field.
func ByWebSearchPricePerCall(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebSearchPricePerCall, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, GroupTable, GroupColumn),
	)
}
