// Code generated by ent, DO NOT EDIT.

package billingprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldGroupID, v))
}

// BalanceRateMultiplier applies equality check predicate on the "balance_rate_multiplier" field. It's identical to BalanceRateMultiplierEQ.
func BalanceRateMultiplier(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldBalanceRateMultiplier, v))
}

// PeakRateEnabled applies equality check predicate on the "peak_rate_enabled" field. It's identical to PeakRateEnabledEQ.
func PeakRateEnabled(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldPeakRateEnabled, v))
}

// PeakStart applies equality check predicate on the "peak_start" field. It's identical to PeakStartEQ.
func PeakStart(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldPeakStart, v))
}

// PeakEnd applies equality check predicate on the "peak_end" field. It's identical to PeakEndEQ.
func PeakEnd(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldPeakEnd, v))
}

// PeakRateMultiplier applies equality check predicate on the "peak_rate_multiplier" field. It's identical to PeakRateMultiplierEQ.
func PeakRateMultiplier(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldPeakRateMultiplier, v))
}

// ImageRateIndependent applies equality check predicate on the "image_rate_independent" field. It's identical to ImageRateIndependentEQ.
func ImageRateIndependent(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImageRateIndependent, v))
}

// ImageRateMultiplier applies equality check predicate on the "image_rate_multiplier" field. It's identical to ImageRateMultiplierEQ.
func ImageRateMultiplier(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImageRateMultiplier, v))
}

// ImagePrice1k applies equality check predicate on the "image_price_1k" field. It's identical to ImagePrice1kEQ.
func ImagePrice1k(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImagePrice1k, v))
}

// ImagePrice2k applies equality check predicate on the "image_price_2k" field. It's identical to ImagePrice2kEQ.
func ImagePrice2k(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImagePrice2k, v))
}

// ImagePrice4k applies equality check predicate on the "image_price_4k" field. It's identical to ImagePrice4kEQ.
func ImagePrice4k(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImagePrice4k, v))
}

// BatchImageDiscountMultiplier applies equality check predicate on the "batch_image_discount_multiplier" field. It's identical to BatchImageDiscountMultiplierEQ.
func BatchImageDiscountMultiplier(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldBatchImageDiscountMultiplier, v))
}

// BatchImageHoldMultiplier applies equality check predicate on the "batch_image_hold_multiplier" field. It's identical to BatchImageHoldMultiplierEQ.
func BatchImageHoldMultiplier(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldBatchImageHoldMultiplier, v))
}

// VideoRateIndependent applies equality check predicate on the "video_rate_independent" field. It's identical to VideoRateIndependentEQ.
func VideoRateIndependent(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoRateIndependent, v))
}

// VideoRateMultiplier applies equality check predicate on the "video_rate_multiplier" field. It's identical to VideoRateMultiplierEQ.
func VideoRateMultiplier(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoRateMultiplier, v))
}

// VideoPrice480p applies equality check predicate on the "video_price_480p" field. It's identical to VideoPrice480pEQ.
func VideoPrice480p(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoPrice480p, v))
}

// VideoPrice720p applies equality check predicate on the "video_price_720p" field. It's identical to VideoPrice720pEQ.
func VideoPrice720p(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoPrice720p, v))
}

// VideoPrice1080p applies equality check predicate on the "video_price_1080p" field. It's identical to VideoPrice1080pEQ.
func VideoPrice1080p(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoPrice1080p, v))
}

// WebSearchPricePerCall applies equality check predicate on the "web_search_price_per_call" field. It's identical to WebSearchPricePerCallEQ.
func WebSearchPricePerCall(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldWebSearchPricePerCall, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldGroupID, vs...))
}

// BalanceRateMultiplierEQ applies the EQ predicate on the "balance_rate_multiplier" field.
func BalanceRateMultiplierEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldBalanceRateMultiplier, v))
}

// BalanceRateMultiplierNEQ applies the NEQ predicate on the "balance_rate_multiplier" field.
func BalanceRateMultiplierNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldBalanceRateMultiplier, v))
}

// BalanceRateMultiplierIn applies the In predicate on the "balance_rate_multiplier" field.
func BalanceRateMultiplierIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldBalanceRateMultiplier, vs...))
}

// BalanceRateMultiplierNotIn applies the NotIn predicate on the "balance_rate_multiplier" field.
func BalanceRateMultiplierNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldBalanceRateMultiplier, vs...))
}

// BalanceRateMultiplierGT applies the GT predicate on the "balance_rate_multiplier" field.
func BalanceRateMultiplierGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldBalanceRateMultiplier, v))
}

// BalanceRateMultiplierGTE applies the GTE predicate on the "balance_rate_multiplier" field.
func BalanceRateMultiplierGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldBalanceRateMultiplier, v))
}

// BalanceRateMultiplierLT applies the LT predicate on the "balance_rate_multiplier" field.
func BalanceRateMultiplierLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldBalanceRateMultiplier, v))
}

// BalanceRateMultiplierLTE applies the LTE predicate on the "balance_rate_multiplier" field.
func BalanceRateMultiplierLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldBalanceRateMultiplier, v))
}

// PeakRateEnabledEQ applies the EQ predicate on the "peak_rate_enabled" field.
func PeakRateEnabledEQ(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldPeakRateEnabled, v))
}

// PeakRateEnabledNEQ applies the NEQ predicate on the "peak_rate_enabled" field.
func PeakRateEnabledNEQ(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldPeakRateEnabled, v))
}

// PeakStartEQ applies the EQ predicate on the "peak_start" field.
func PeakStartEQ(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldPeakStart, v))
}

// PeakStartNEQ applies the NEQ predicate on the "peak_start" field.
func PeakStartNEQ(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldPeakStart, v))
}

// PeakStartIn applies the In predicate on the "peak_start" field.
func PeakStartIn(vs ...string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldPeakStart, vs...))
}

// PeakStartNotIn applies the NotIn predicate on the "peak_start" field.
func PeakStartNotIn(vs ...string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldPeakStart, vs...))
}

// PeakStartGT applies the GT predicate on the "peak_start" field.
func PeakStartGT(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldPeakStart, v))
}

// PeakStartGTE applies the GTE predicate on the "peak_start" field.
func PeakStartGTE(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldPeakStart, v))
}

// PeakStartLT applies the LT predicate on the "peak_start" field.
func PeakStartLT(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldPeakStart, v))
}

// PeakStartLTE applies the LTE predicate on the "peak_start" field.
func PeakStartLTE(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldPeakStart, v))
}

// PeakStartContains applies the Contains predicate on the "peak_start" field.
func PeakStartContains(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldContains(FieldPeakStart, v))
}

// PeakStartHasPrefix applies the HasPrefix predicate on the "peak_start" field.
func PeakStartHasPrefix(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldHasPrefix(FieldPeakStart, v))
}

// PeakStartHasSuffix applies the HasSuffix predicate on the "peak_start" field.
func PeakStartHasSuffix(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldHasSuffix(FieldPeakStart, v))
}

// PeakStartEqualFold applies the EqualFold predicate on the "peak_start" field.
func PeakStartEqualFold(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEqualFold(FieldPeakStart, v))
}

// PeakStartContainsFold applies the ContainsFold predicate on the "peak_start" field.
func PeakStartContainsFold(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldContainsFold(FieldPeakStart, v))
}

// PeakEndEQ applies the EQ predicate on the "peak_end" field.
func PeakEndEQ(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldPeakEnd, v))
}

// PeakEndNEQ applies the NEQ predicate on the "peak_end" field.
func PeakEndNEQ(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldPeakEnd, v))
}

// PeakEndIn applies the In predicate on the "peak_end" field.
func PeakEndIn(vs ...string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldPeakEnd, vs...))
}

// PeakEndNotIn applies the NotIn predicate on the "peak_end" field.
func PeakEndNotIn(vs ...string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldPeakEnd, vs...))
}

// PeakEndGT applies the GT predicate on the "peak_end" field.
func PeakEndGT(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldPeakEnd, v))
}

// PeakEndGTE applies the GTE predicate on the "peak_end" field.
func PeakEndGTE(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldPeakEnd, v))
}

// PeakEndLT applies the LT predicate on the "peak_end" field.
func PeakEndLT(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldPeakEnd, v))
}

// PeakEndLTE applies the LTE predicate on the "peak_end" field.
func PeakEndLTE(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldPeakEnd, v))
}

// PeakEndContains applies the Contains predicate on the "peak_end" field.
func PeakEndContains(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldContains(FieldPeakEnd, v))
}

// PeakEndHasPrefix applies the HasPrefix predicate on the "peak_end" field.
func PeakEndHasPrefix(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldHasPrefix(FieldPeakEnd, v))
}

// PeakEndHasSuffix applies the HasSuffix predicate on the "peak_end" field.
func PeakEndHasSuffix(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldHasSuffix(FieldPeakEnd, v))
}

// PeakEndEqualFold applies the EqualFold predicate on the "peak_end" field.
func PeakEndEqualFold(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEqualFold(FieldPeakEnd, v))
}

// PeakEndContainsFold applies the ContainsFold predicate on the "peak_end" field.
func PeakEndContainsFold(v string) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldContainsFold(FieldPeakEnd, v))
}

// PeakRateMultiplierEQ applies the EQ predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierNEQ applies the NEQ predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierIn applies the In predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldPeakRateMultiplier, vs...))
}

// PeakRateMultiplierNotIn applies the NotIn predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldPeakRateMultiplier, vs...))
}

// PeakRateMultiplierGT applies the GT predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierGTE applies the GTE predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierLT applies the LT predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierLTE applies the LTE predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldPeakRateMultiplier, v))
}

// ImageRateIndependentEQ applies the EQ predicate on the "image_rate_independent" field.
func ImageRateIndependentEQ(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImageRateIndependent, v))
}

// ImageRateIndependentNEQ applies the NEQ predicate on the "image_rate_independent" field.
func ImageRateIndependentNEQ(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldImageRateIndependent, v))
}

// ImageRateMultiplierEQ applies the EQ predicate on the "image_rate_multiplier" field.
func ImageRateMultiplierEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImageRateMultiplier, v))
}

// ImageRateMultiplierNEQ applies the NEQ predicate on the "image_rate_multiplier" field.
func ImageRateMultiplierNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldImageRateMultiplier, v))
}

// ImageRateMultiplierIn applies the In predicate on the "image_rate_multiplier" field.
func ImageRateMultiplierIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldImageRateMultiplier, vs...))
}

// ImageRateMultiplierNotIn applies the NotIn predicate on the "image_rate_multiplier" field.
func ImageRateMultiplierNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldImageRateMultiplier, vs...))
}

// ImageRateMultiplierGT applies the GT predicate on the "image_rate_multiplier" field.
func ImageRateMultiplierGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldImageRateMultiplier, v))
}

// ImageRateMultiplierGTE applies the GTE predicate on the "image_rate_multiplier" field.
func ImageRateMultiplierGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldImageRateMultiplier, v))
}

// ImageRateMultiplierLT applies the LT predicate on the "image_rate_multiplier" field.
func ImageRateMultiplierLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldImageRateMultiplier, v))
}

// ImageRateMultiplierLTE applies the LTE predicate on the "image_rate_multiplier" field.
func ImageRateMultiplierLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldImageRateMultiplier, v))
}

// ImagePrice1kEQ applies the EQ predicate on the "image_price_1k" field.
func ImagePrice1kEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImagePrice1k, v))
}

// ImagePrice1kNEQ applies the NEQ predicate on the "image_price_1k" field.
func ImagePrice1kNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldImagePrice1k, v))
}

// ImagePrice1kIn applies the In predicate on the "image_price_1k" field.
func ImagePrice1kIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldImagePrice1k, vs...))
}

// ImagePrice1kNotIn applies the NotIn predicate on the "image_price_1k" field.
func ImagePrice1kNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldImagePrice1k, vs...))
}

// ImagePrice1kGT applies the GT predicate on the "image_price_1k" field.
func ImagePrice1kGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldImagePrice1k, v))
}

// ImagePrice1kGTE applies the GTE predicate on the "image_price_1k" field.
func ImagePrice1kGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldImagePrice1k, v))
}

// ImagePrice1kLT applies the LT predicate on the "image_price_1k" field.
func ImagePrice1kLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldImagePrice1k, v))
}

// ImagePrice1kLTE applies the LTE predicate on the "image_price_1k" field.
func ImagePrice1kLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldImagePrice1k, v))
}

// ImagePrice1kIsNil applies the IsNil predicate on the "image_price_1k" field.
func ImagePrice1kIsNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIsNull(FieldImagePrice1k))
}

// ImagePrice1kNotNil applies the NotNil predicate on the "image_price_1k" field.
func ImagePrice1kNotNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotNull(FieldImagePrice1k))
}

// ImagePrice2kEQ applies the EQ predicate on the "image_price_2k" field.
func ImagePrice2kEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImagePrice2k, v))
}

// ImagePrice2kNEQ applies the NEQ predicate on the "image_price_2k" field.
func ImagePrice2kNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldImagePrice2k, v))
}

// ImagePrice2kIn applies the In predicate on the "image_price_2k" field.
func ImagePrice2kIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldImagePrice2k, vs...))
}

// ImagePrice2kNotIn applies the NotIn predicate on the "image_price_2k" field.
func ImagePrice2kNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldImagePrice2k, vs...))
}

// ImagePrice2kGT applies the GT predicate on the "image_price_2k" field.
func ImagePrice2kGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldImagePrice2k, v))
}

// ImagePrice2kGTE applies the GTE predicate on the "image_price_2k" field.
func ImagePrice2kGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldImagePrice2k, v))
}

// ImagePrice2kLT applies the LT predicate on the "image_price_2k" field.
func ImagePrice2kLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldImagePrice2k, v))
}

// ImagePrice2kLTE applies the LTE predicate on the "image_price_2k" field.
func ImagePrice2kLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldImagePrice2k, v))
}

// ImagePrice2kIsNil applies the IsNil predicate on the "image_price_2k" field.
func ImagePrice2kIsNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIsNull(FieldImagePrice2k))
}

// ImagePrice2kNotNil applies the NotNil predicate on the "image_price_2k" field.
func ImagePrice2kNotNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotNull(FieldImagePrice2k))
}

// ImagePrice4kEQ applies the EQ predicate on the "image_price_4k" field.
func ImagePrice4kEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldImagePrice4k, v))
}

// ImagePrice4kNEQ applies the NEQ predicate on the "image_price_4k" field.
func ImagePrice4kNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldImagePrice4k, v))
}

// ImagePrice4kIn applies the In predicate on the "image_price_4k" field.
func ImagePrice4kIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldImagePrice4k, vs...))
}

// ImagePrice4kNotIn applies the NotIn predicate on the "image_price_4k" field.
func ImagePrice4kNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldImagePrice4k, vs...))
}

// ImagePrice4kGT applies the GT predicate on the "image_price_4k" field.
func ImagePrice4kGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldImagePrice4k, v))
}

// ImagePrice4kGTE applies the GTE predicate on the "image_price_4k" field.
func ImagePrice4kGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldImagePrice4k, v))
}

// ImagePrice4kLT applies the LT predicate on the "image_price_4k" field.
func ImagePrice4kLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldImagePrice4k, v))
}

// ImagePrice4kLTE applies the LTE predicate on the "image_price_4k" field.
func ImagePrice4kLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldImagePrice4k, v))
}

// ImagePrice4kIsNil applies the IsNil predicate on the "image_price_4k" field.
func ImagePrice4kIsNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIsNull(FieldImagePrice4k))
}

// ImagePrice4kNotNil applies the NotNil predicate on the "image_price_4k" field.
func ImagePrice4kNotNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotNull(FieldImagePrice4k))
}

// BatchImageDiscountMultiplierEQ applies the EQ predicate on the "batch_image_discount_multiplier" field.
func BatchImageDiscountMultiplierEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldBatchImageDiscountMultiplier, v))
}

// BatchImageDiscountMultiplierNEQ applies the NEQ predicate on the "batch_image_discount_multiplier" field.
func BatchImageDiscountMultiplierNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldBatchImageDiscountMultiplier, v))
}

// BatchImageDiscountMultiplierIn applies the In predicate on the "batch_image_discount_multiplier" field.
func BatchImageDiscountMultiplierIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldBatchImageDiscountMultiplier, vs...))
}

// BatchImageDiscountMultiplierNotIn applies the NotIn predicate on the "batch_image_discount_multiplier" field.
func BatchImageDiscountMultiplierNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldBatchImageDiscountMultiplier, vs...))
}

// BatchImageDiscountMultiplierGT applies the GT predicate on the "batch_image_discount_multiplier" field.
func BatchImageDiscountMultiplierGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldBatchImageDiscountMultiplier, v))
}

// BatchImageDiscountMultiplierGTE applies the GTE predicate on the "batch_image_discount_multiplier" field.
func BatchImageDiscountMultiplierGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldBatchImageDiscountMultiplier, v))
}

// BatchImageDiscountMultiplierLT applies the LT predicate on the "batch_image_discount_multiplier" field.
func BatchImageDiscountMultiplierLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldBatchImageDiscountMultiplier, v))
}

// BatchImageDiscountMultiplierLTE applies the LTE predicate on the "batch_image_discount_multiplier" field.
func BatchImageDiscountMultiplierLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldBatchImageDiscountMultiplier, v))
}

// BatchImageHoldMultiplierEQ applies the EQ predicate on the "batch_image_hold_multiplier" field.
func BatchImageHoldMultiplierEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldBatchImageHoldMultiplier, v))
}

// BatchImageHoldMultiplierNEQ applies the NEQ predicate on the "batch_image_hold_multiplier" field.
func BatchImageHoldMultiplierNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldBatchImageHoldMultiplier, v))
}

// BatchImageHoldMultiplierIn applies the In predicate on the "batch_image_hold_multiplier" field.
func BatchImageHoldMultiplierIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldBatchImageHoldMultiplier, vs...))
}

// BatchImageHoldMultiplierNotIn applies the NotIn predicate on the "batch_image_hold_multiplier" field.
func BatchImageHoldMultiplierNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldBatchImageHoldMultiplier, vs...))
}

// BatchImageHoldMultiplierGT applies the GT predicate on the "batch_image_hold_multiplier" field.
func BatchImageHoldMultiplierGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldBatchImageHoldMultiplier, v))
}

// BatchImageHoldMultiplierGTE applies the GTE predicate on the "batch_image_hold_multiplier" field.
func BatchImageHoldMultiplierGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldBatchImageHoldMultiplier, v))
}

// BatchImageHoldMultiplierLT applies the LT predicate on the "batch_image_hold_multiplier" field.
func BatchImageHoldMultiplierLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldBatchImageHoldMultiplier, v))
}

// BatchImageHoldMultiplierLTE applies the LTE predicate on the "batch_image_hold_multiplier" field.
func BatchImageHoldMultiplierLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldBatchImageHoldMultiplier, v))
}

// VideoRateIndependentEQ applies the EQ predicate on the "video_rate_independent" field.
func VideoRateIndependentEQ(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoRateIndependent, v))
}

// VideoRateIndependentNEQ applies the NEQ predicate on the "video_rate_independent" field.
func VideoRateIndependentNEQ(v bool) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldVideoRateIndependent, v))
}

// VideoRateMultiplierEQ applies the EQ predicate on the "video_rate_multiplier" field.
func VideoRateMultiplierEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoRateMultiplier, v))
}

// VideoRateMultiplierNEQ applies the NEQ predicate on the "video_rate_multiplier" field.
func VideoRateMultiplierNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldVideoRateMultiplier, v))
}

// VideoRateMultiplierIn applies the In predicate on the "video_rate_multiplier" field.
func VideoRateMultiplierIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldVideoRateMultiplier, vs...))
}

// VideoRateMultiplierNotIn applies the NotIn predicate on the "video_rate_multiplier" field.
func VideoRateMultiplierNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldVideoRateMultiplier, vs...))
}

// VideoRateMultiplierGT applies the GT predicate on the "video_rate_multiplier" field.
func VideoRateMultiplierGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldVideoRateMultiplier, v))
}

// VideoRateMultiplierGTE applies the GTE predicate on the "video_rate_multiplier" field.
func VideoRateMultiplierGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldVideoRateMultiplier, v))
}

// VideoRateMultiplierLT applies the LT predicate on the "video_rate_multiplier" field.
func VideoRateMultiplierLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldVideoRateMultiplier, v))
}

// VideoRateMultiplierLTE applies the LTE predicate on the "video_rate_multiplier" field.
func VideoRateMultiplierLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldVideoRateMultiplier, v))
}

// VideoPrice480pEQ applies the EQ predicate on the "video_price_480p" field.
func VideoPrice480pEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoPrice480p, v))
}

// VideoPrice480pNEQ applies the NEQ predicate on the "video_price_480p" field.
func VideoPrice480pNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldVideoPrice480p, v))
}

// VideoPrice480pIn applies the In predicate on the "video_price_480p" field.
func VideoPrice480pIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldVideoPrice480p, vs...))
}

// VideoPrice480pNotIn applies the NotIn predicate on the "video_price_480p" field.
func VideoPrice480pNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldVideoPrice480p, vs...))
}

// VideoPrice480pGT applies the GT predicate on the "video_price_480p" field.
func VideoPrice480pGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldVideoPrice480p, v))
}

// VideoPrice480pGTE applies the GTE predicate on the "video_price_480p" field.
func VideoPrice480pGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldVideoPrice480p, v))
}

// VideoPrice480pLT applies the LT predicate on the "video_price_480p" field.
func VideoPrice480pLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldVideoPrice480p, v))
}

// VideoPrice480pLTE applies the LTE predicate on the "video_price_480p" field.
func VideoPrice480pLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldVideoPrice480p, v))
}

// VideoPrice480pIsNil applies the IsNil predicate on the "video_price_480p" field.
func VideoPrice480pIsNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIsNull(FieldVideoPrice480p))
}

// VideoPrice480pNotNil applies the NotNil predicate on the "video_price_480p" field.
func VideoPrice480pNotNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotNull(FieldVideoPrice480p))
}

// VideoPrice720pEQ applies the EQ predicate on the "video_price_720p" field.
func VideoPrice720pEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoPrice720p, v))
}

// VideoPrice720pNEQ applies the NEQ predicate on the "video_price_720p" field.
func VideoPrice720pNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldVideoPrice720p, v))
}

// VideoPrice720pIn applies the In predicate on the "video_price_720p" field.
func VideoPrice720pIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldVideoPrice720p, vs...))
}

// VideoPrice720pNotIn applies the NotIn predicate on the "video_price_720p" field.
func VideoPrice720pNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldVideoPrice720p, vs...))
}

// VideoPrice720pGT applies the GT predicate on the "video_price_720p" field.
func VideoPrice720pGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldVideoPrice720p, v))
}

// VideoPrice720pGTE applies the GTE predicate on the "video_price_720p" field.
func VideoPrice720pGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldVideoPrice720p, v))
}

// VideoPrice720pLT applies the LT predicate on the "video_price_720p" field.
func VideoPrice720pLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldVideoPrice720p, v))
}

// VideoPrice720pLTE applies the LTE predicate on the "video_price_720p" field.
func VideoPrice720pLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldVideoPrice720p, v))
}

// VideoPrice720pIsNil applies the IsNil predicate on the "video_price_720p" field.
func VideoPrice720pIsNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIsNull(FieldVideoPrice720p))
}

// VideoPrice720pNotNil applies the NotNil predicate on the "video_price_720p" field.
func VideoPrice720pNotNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotNull(FieldVideoPrice720p))
}

// VideoPrice1080pEQ applies the EQ predicate on the "video_price_1080p" field.
func VideoPrice1080pEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldVideoPrice1080p, v))
}

// VideoPrice1080pNEQ applies the NEQ predicate on the "video_price_1080p" field.
func VideoPrice1080pNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldVideoPrice1080p, v))
}

// VideoPrice1080pIn applies the In predicate on the "video_price_1080p" field.
func VideoPrice1080pIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldVideoPrice1080p, vs...))
}

// VideoPrice1080pNotIn applies the NotIn predicate on the "video_price_1080p" field.
func VideoPrice1080pNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldVideoPrice1080p, vs...))
}

// VideoPrice1080pGT applies the GT predicate on the "video_price_1080p" field.
func VideoPrice1080pGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldVideoPrice1080p, v))
}

// VideoPrice1080pGTE applies the GTE predicate on the "video_price_1080p" field.
func VideoPrice1080pGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldVideoPrice1080p, v))
}

// VideoPrice1080pLT applies the LT predicate on the "video_price_1080p" field.
func VideoPrice1080pLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldVideoPrice1080p, v))
}

// VideoPrice1080pLTE applies the LTE predicate on the "video_price_1080p" field.
func VideoPrice1080pLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldVideoPrice1080p, v))
}

// VideoPrice1080pIsNil applies the IsNil predicate on the "video_price_1080p" field.
func VideoPrice1080pIsNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIsNull(FieldVideoPrice1080p))
}

// VideoPrice1080pNotNil applies the NotNil predicate on the "video_price_1080p" field.
func VideoPrice1080pNotNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotNull(FieldVideoPrice1080p))
}

// WebSearchPricePerCallEQ applies the EQ predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldEQ(FieldWebSearchPricePerCall, v))
}

// WebSearchPricePerCallNEQ applies the NEQ predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallNEQ(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNEQ(FieldWebSearchPricePerCall, v))
}

// WebSearchPricePerCallIn applies the In predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIn(FieldWebSearchPricePerCall, vs...))
}

// WebSearchPricePerCallNotIn applies the NotIn predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallNotIn(vs ...float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotIn(FieldWebSearchPricePerCall, vs...))
}

// WebSearchPricePerCallGT applies the GT predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallGT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGT(FieldWebSearchPricePerCall, v))
}

// WebSearchPricePerCallGTE applies the GTE predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallGTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldGTE(FieldWebSearchPricePerCall, v))
}

// WebSearchPricePerCallLT applies the LT predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallLT(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLT(FieldWebSearchPricePerCall, v))
}

// WebSearchPricePerCallLTE applies the LTE predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallLTE(v float64) predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldLTE(FieldWebSearchPricePerCall, v))
}

// WebSearchPricePerCallIsNil applies the IsNil predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallIsNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldIsNull(FieldWebSearchPricePerCall))
}

// WebSearchPricePerCallNotNil applies the NotNil predicate on the "web_search_price_per_call" field.
func WebSearchPricePerCallNotNil() predicate.BillingProfile {
	return predicate.BillingProfile(sql.FieldNotNull(FieldWebSearchPricePerCall))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.BillingProfile {
	return predicate.BillingProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.BillingProfile {
	return predicate.BillingProfile(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingProfile) predicate.BillingProfile {
	return predicate.BillingProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingProfile) predicate.BillingProfile {
	return predicate.BillingProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingProfile) predicate.BillingProfile {
	return predicate.BillingProfile(sql.NotPredicates(p))
}
