// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/billingprofile"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// BillingProfileCreate is the builder for creating a BillingProfile entity.
type BillingProfileCreate struct {
	config
	mutation *BillingProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BillingProfileCreate) SetCreatedAt(v time.Time) *BillingProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableCreatedAt(v *time.Time) *BillingProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BillingProfileCreate) SetUpdatedAt(v time.Time) *BillingProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableUpdatedAt(v *time.Time) *BillingProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *BillingProfileCreate) SetGroupID(v int64) *BillingProfileCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetBalanceRateMultiplier sets the "balance_rate_multiplier" field.
func (_c *BillingProfileCreate) SetBalanceRateMultiplier(v float64) *BillingProfileCreate {
	_c.mutation.SetBalanceRateMultiplier(v)
	return _c
}

// SetNillableBalanceRateMultiplier sets the "balance_rate_multiplier" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableBalanceRateMultiplier(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetBalanceRateMultiplier(*v)
	}
	return _c
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (_c *BillingProfileCreate) SetPeakRateEnabled(v bool) *BillingProfileCreate {
	_c.mutation.SetPeakRateEnabled(v)
	return _c
}

// SetNillablePeakRateEnabled sets the "peak_rate_enabled" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillablePeakRateEnabled(v *bool) *BillingProfileCreate {
	if v != nil {
		_c.SetPeakRateEnabled(*v)
	}
	return _c
}

// SetPeakStart sets the "peak_start" field.
func (_c *BillingProfileCreate) SetPeakStart(v string) *BillingProfileCreate {
	_c.mutation.SetPeakStart(v)
	return _c
}

// SetNillablePeakStart sets the "peak_start" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillablePeakStart(v *string) *BillingProfileCreate {
	if v != nil {
		_c.SetPeakStart(*v)
	}
	return _c
}

// SetPeakEnd sets the "peak_end" field.
func (_c *BillingProfileCreate) SetPeakEnd(v string) *BillingProfileCreate {
	_c.mutation.SetPeakEnd(v)
	return _c
}

// SetNillablePeakEnd sets the "peak_end" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillablePeakEnd(v *string) *BillingProfileCreate {
	if v != nil {
		_c.SetPeakEnd(*v)
	}
	return _c
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (_c *BillingProfileCreate) SetPeakRateMultiplier(v float64) *BillingProfileCreate {
	_c.mutation.SetPeakRateMultiplier(v)
	return _c
}

// SetNillablePeakRateMultiplier sets the "peak_rate_multiplier" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillablePeakRateMultiplier(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetPeakRateMultiplier(*v)
	}
	return _c
}

// SetImageRateIndependent sets the "image_rate_independent" field.
func (_c *BillingProfileCreate) SetImageRateIndependent(v bool) *BillingProfileCreate {
	_c.mutation.SetImageRateIndependent(v)
	return _c
}

// SetNillableImageRateIndependent sets the "image_rate_independent" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableImageRateIndependent(v *bool) *BillingProfileCreate {
	if v != nil {
		_c.SetImageRateIndependent(*v)
	}
	return _c
}

// SetImageRateMultiplier sets the "image_rate_multiplier" field.
func (_c *BillingProfileCreate) SetImageRateMultiplier(v float64) *BillingProfileCreate {
	_c.mutation.SetImageRateMultiplier(v)
	return _c
}

// SetNillableImageRateMultiplier sets the "image_rate_multiplier" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableImageRateMultiplier(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetImageRateMultiplier(*v)
	}
	return _c
}

// SetImagePrice1k sets the "image_price_1k" field.
func (_c *BillingProfileCreate) SetImagePrice1k(v float64) *BillingProfileCreate {
	_c.mutation.SetImagePrice1k(v)
	return _c
}

// SetNillableImagePrice1k sets the "image_price_1k" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableImagePrice1k(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetImagePrice1k(*v)
	}
	return _c
}

// SetImagePrice2k sets the "image_price_2k" field.
func (_c *BillingProfileCreate) SetImagePrice2k(v float64) *BillingProfileCreate {
	_c.mutation.SetImagePrice2k(v)
	return _c
}

// SetNillableImagePrice2k sets the "image_price_2k" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableImagePrice2k(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetImagePrice2k(*v)
	}
	return _c
}

// SetImagePrice4k sets the "image_price_4k" field.
func (_c *BillingProfileCreate) SetImagePrice4k(v float64) *BillingProfileCreate {
	_c.mutation.SetImagePrice4k(v)
	return _c
}

// SetNillableImagePrice4k sets the "image_price_4k" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableImagePrice4k(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetImagePrice4k(*v)
	}
	return _c
}

// SetBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field.
func (_c *BillingProfileCreate) SetBatchImageDiscountMultiplier(v float64) *BillingProfileCreate {
	_c.mutation.SetBatchImageDiscountMultiplier(v)
	return _c
}

// SetNillableBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableBatchImageDiscountMultiplier(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetBatchImageDiscountMultiplier(*v)
	}
	return _c
}

// SetBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field.
func (_c *BillingProfileCreate) SetBatchImageHoldMultiplier(v float64) *BillingProfileCreate {
	_c.mutation.SetBatchImageHoldMultiplier(v)
	return _c
}

// SetNillableBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableBatchImageHoldMultiplier(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetBatchImageHoldMultiplier(*v)
	}
	return _c
}

// SetVideoRateIndependent sets the "video_rate_independent" field.
func (_c *BillingProfileCreate) SetVideoRateIndependent(v bool) *BillingProfileCreate {
	_c.mutation.SetVideoRateIndependent(v)
	return _c
}

// SetNillableVideoRateIndependent sets the "video_rate_independent" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableVideoRateIndependent(v *bool) *BillingProfileCreate {
	if v != nil {
		_c.SetVideoRateIndependent(*v)
	}
	return _c
}

// SetVideoRateMultiplier sets the "video_rate_multiplier" field.
func (_c *BillingProfileCreate) SetVideoRateMultiplier(v float64) *BillingProfileCreate {
	_c.mutation.SetVideoRateMultiplier(v)
	return _c
}

// SetNillableVideoRateMultiplier sets the "video_rate_multiplier" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableVideoRateMultiplier(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetVideoRateMultiplier(*v)
	}
	return _c
}

// SetVideoPrice480p sets the "video_price_480p" field.
func (_c *BillingProfileCreate) SetVideoPrice480p(v float64) *BillingProfileCreate {
	_c.mutation.SetVideoPrice480p(v)
	return _c
}

// SetNillableVideoPrice480p sets the "video_price_480p" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableVideoPrice480p(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetVideoPrice480p(*v)
	}
	return _c
}

// SetVideoPrice720p sets the "video_price_720p" field.
func (_c *BillingProfileCreate) SetVideoPrice720p(v float64) *BillingProfileCreate {
	_c.mutation.SetVideoPrice720p(v)
	return _c
}

// SetNillableVideoPrice720p sets the "video_price_720p" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableVideoPrice720p(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetVideoPrice720p(*v)
	}
	return _c
}

// SetVideoPrice1080p sets the "video_price_1080p" field.
func (_c *BillingProfileCreate) SetVideoPrice1080p(v float64) *BillingProfileCreate {
	_c.mutation.SetVideoPrice1080p(v)
	return _c
}

// SetNillableVideoPrice1080p sets the "video_price_1080p" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableVideoPrice1080p(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetVideoPrice1080p(*v)
	}
	return _c
}

// SetWebSearchPricePerCall sets the "web_search_price_per_call" field.
func (_c *BillingProfileCreate) SetWebSearchPricePerCall(v float64) *BillingProfileCreate {
	_c.mutation.SetWebSearchPricePerCall(v)
	return _c
}

// SetNillableWebSearchPricePerCall sets the "web_search_price_per_call" field if the given value is not nil.
func (_c *BillingProfileCreate) SetNillableWebSearchPricePerCall(v *float64) *BillingProfileCreate {
	if v != nil {
		_c.SetWebSearchPricePerCall(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *BillingProfileCreate) SetGroup(v *Group) *BillingProfileCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the BillingProfileMutation object of the builder.
func (_c *BillingProfileCreate) Mutation() *BillingProfileMutation {
	return _c.mutation
}

// Save creates the BillingProfile in the database.
func (_c *BillingProfileCreate) Save(ctx context.Context) (*BillingProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillingProfileCreate) SaveX(ctx context.Context) *BillingProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillingProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := billingprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := billingprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.BalanceRateMultiplier(); !ok {
		v := billingprofile.DefaultBalanceRateMultiplier
		_c.mutation.SetBalanceRateMultiplier(v)
	}
	if _, ok := _c.mutation.PeakRateEnabled(); !ok {
		v := billingprofile.DefaultPeakRateEnabled
		_c.mutation.SetPeakRateEnabled(v)
	}
	if _, ok := _c.mutation.PeakStart(); !ok {
		v := billingprofile.DefaultPeakStart
		_c.mutation.SetPeakStart(v)
	}
	if _, ok := _c.mutation.PeakEnd(); !ok {
		v := billingprofile.DefaultPeakEnd
		_c.mutation.SetPeakEnd(v)
	}
	if _, ok := _c.mutation.PeakRateMultiplier(); !ok {
		v := billingprofile.DefaultPeakRateMultiplier
		_c.mutation.SetPeakRateMultiplier(v)
	}
	if _, ok := _c.mutation.ImageRateIndependent(); !ok {
		v := billingprofile.DefaultImageRateIndependent
		_c.mutation.SetImageRateIndependent(v)
	}
	if _, ok := _c.mutation.ImageRateMultiplier(); !ok {
		v := billingprofile.DefaultImageRateMultiplier
		_c.mutation.SetImageRateMultiplier(v)
	}
	if _, ok := _c.mutation.BatchImageDiscountMultiplier(); !ok {
		v := billingprofile.DefaultBatchImageDiscountMultiplier
		_c.mutation.SetBatchImageDiscountMultiplier(v)
	}
	if _, ok := _c.mutation.BatchImageHoldMultiplier(); !ok {
		v := billingprofile.DefaultBatchImageHoldMultiplier
		_c.mutation.SetBatchImageHoldMultiplier(v)
	}
	if _, ok := _c.mutation.VideoRateIndependent(); !ok {
		v := billingprofile.DefaultVideoRateIndependent
		_c.mutation.SetVideoRateIndependent(v)
	}
	if _, ok := _c.mutation.VideoRateMultiplier(); !ok {
		v := billingprofile.DefaultVideoRateMultiplier
		_c.mutation.SetVideoRateMultiplier(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillingProfileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BillingProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BillingProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "BillingProfile.group_id"`)}
	}
	if _, ok := _c.mutation.BalanceRateMultiplier(); !ok {
		return &ValidationError{Name: "balance_rate_multiplier", err: errors.New(`ent: missing required field "BillingProfile.balance_rate_multiplier"`)}
	}
	if _, ok := _c.mutation.PeakRateEnabled(); !ok {
		return &ValidationError{Name: "peak_rate_enabled", err: errors.New(`ent: missing required field "BillingProfile.peak_rate_enabled"`)}
	}
	if _, ok := _c.mutation.PeakStart(); !ok {
		return &ValidationError{Name: "peak_start", err: errors.New(`ent: missing required field "BillingProfile.peak_start"`)}
	}
	if v, ok := _c.mutation.PeakStart(); ok {
		if err := billingprofile.PeakStartValidator(v); err != nil {
			return &ValidationError{Name: "peak_start", err: fmt.Errorf(`ent: validator failed for field "BillingProfile.peak_start": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeakEnd(); !ok {
		return &ValidationError{Name: "peak_end", err: errors.New(`ent: missing required field "BillingProfile.peak_end"`)}
	}
	if v, ok := _c.mutation.PeakEnd(); ok {
		if err := billingprofile.PeakEndValidator(v); err != nil {
			return &ValidationError{Name: "peak_end", err: fmt.Errorf(`ent: validator failed for field "BillingProfile.peak_end": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeakRateMultiplier(); !ok {
		return &ValidationError{Name: "peak_rate_multiplier", err: errors.New(`ent: missing required field "BillingProfile.peak_rate_multiplier"`)}
	}
	if _, ok := _c.mutation.ImageRateIndependent(); !ok {
		return &ValidationError{Name: "image_rate_independent", err: errors.New(`ent: missing required field "BillingProfile.image_rate_independent"`)}
	}
	if _, ok := _c.mutation.ImageRateMultiplier(); !ok {
		return &ValidationError{Name: "image_rate_multiplier", err: errors.New(`ent: missing required field "BillingProfile.image_rate_multiplier"`)}
	}
	if _, ok := _c.mutation.BatchImageDiscountMultiplier(); !ok {
		return &ValidationError{Name: "batch_image_discount_multiplier", err: errors.New(`ent: missing required field "BillingProfile.batch_image_discount_multiplier"`)}
	}
	if _, ok := _c.mutation.BatchImageHoldMultiplier(); !ok {
		return &ValidationError{Name: "batch_image_hold_multiplier", err: errors.New(`ent: missing required field "BillingProfile.batch_image_hold_multiplier"`)}
	}
	if _, ok := _c.mutation.VideoRateIndependent(); !ok {
		return &ValidationError{Name: "video_rate_independent", err: errors.New(`ent: missing required field "BillingProfile.video_rate_independent"`)}
	}
	if _, ok := _c.mutation.VideoRateMultiplier(); !ok {
		return &ValidationError{Name: "video_rate_multiplier", err: errors.New(`ent: missing required field "BillingProfile.video_rate_multiplier"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "BillingProfile.group"`)}
	}
	return nil
}

func (_c *BillingProfileCreate) sqlSave(ctx context.Context) (*BillingProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillingProfileCreate) createSpec() (*BillingProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &BillingProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(billingprofile.Table, sqlgraph.NewFieldSpec(billingprofile.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(billingprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(billingprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.BalanceRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBalanceRateMultiplier, field.TypeFloat64, value)
		_node.BalanceRateMultiplier = value
	}
	if value, ok := _c.mutation.PeakRateEnabled(); ok {
		_spec.SetField(billingprofile.FieldPeakRateEnabled, field.TypeBool, value)
		_node.PeakRateEnabled = value
	}
	if value, ok := _c.mutation.PeakStart(); ok {
		_spec.SetField(billingprofile.FieldPeakStart, field.TypeString, value)
		_node.PeakStart = value
	}
	if value, ok := _c.mutation.PeakEnd(); ok {
		_spec.SetField(billingprofile.FieldPeakEnd, field.TypeString, value)
		_node.PeakEnd = value
	}
	if value, ok := _c.mutation.PeakRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldPeakRateMultiplier, field.TypeFloat64, value)
		_node.PeakRateMultiplier = value
	}
	if value, ok := _c.mutation.ImageRateIndependent(); ok {
		_spec.SetField(billingprofile.FieldImageRateIndependent, field.TypeBool, value)
		_node.ImageRateIndependent = value
	}
	if value, ok := _c.mutation.ImageRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldImageRateMultiplier, field.TypeFloat64, value)
		_node.ImageRateMultiplier = value
	}
	if value, ok := _c.mutation.ImagePrice1k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice1k, field.TypeFloat64, value)
		_node.ImagePrice1k = &value
	}
	if value, ok := _c.mutation.ImagePrice2k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice2k, field.TypeFloat64, value)
		_node.ImagePrice2k = &value
	}
	if value, ok := _c.mutation.ImagePrice4k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice4k, field.TypeFloat64, value)
		_node.ImagePrice4k = &value
	}
	if value, ok := _c.mutation.BatchImageDiscountMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBatchImageDiscountMultiplier, field.TypeFloat64, value)
		_node.BatchImageDiscountMultiplier = value
	}
	if value, ok := _c.mutation.BatchImageHoldMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBatchImageHoldMultiplier, field.TypeFloat64, value)
		_node.BatchImageHoldMultiplier = value
	}
	if value, ok := _c.mutation.VideoRateIndependent(); ok {
		_spec.SetField(billingprofile.FieldVideoRateIndependent, field.TypeBool, value)
		_node.VideoRateIndependent = value
	}
	if value, ok := _c.mutation.VideoRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldVideoRateMultiplier, field.TypeFloat64, value)
		_node.VideoRateMultiplier = value
	}
	if value, ok := _c.mutation.VideoPrice480p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice480p, field.TypeFloat64, value)
		_node.VideoPrice480p = &value
	}
	if value, ok := _c.mutation.VideoPrice720p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice720p, field.TypeFloat64, value)
		_node.VideoPrice720p = &value
	}
	if value, ok := _c.mutation.VideoPrice1080p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice1080p, field.TypeFloat64, value)
		_node.VideoPrice1080p = &value
	}
	if value, ok := _c.mutation.WebSearchPricePerCall(); ok {
		_spec.SetField(billingprofile.FieldWebSearchPricePerCall, field.TypeFloat64, value)
		_node.WebSearchPricePerCall = &value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   billingprofile.GroupTable,
			Columns: []string{billingprofile.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingProfile.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingProfileCreate) OnConflict(opts ...sql.ConflictOption) *BillingProfileUpsertOne {
	_c.conflict = opts
	return &BillingProfileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingProfileCreate) OnConflictColumns(columns ...string) *BillingProfileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingProfileUpsertOne{
		create: _c,
	}
}

type (
	// BillingProfileUpsertOne is the builder for "upsert"-ing
	//  one BillingProfile node.
	BillingProfileUpsertOne struct {
		create *BillingProfileCreate
	}

	// BillingProfileUpsert is the "OnConflict" setter.
	BillingProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingProfileUpsert) SetUpdatedAt(v time.Time) *BillingProfileUpsert {
	u.Set(billingprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateUpdatedAt() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *BillingProfileUpsert) SetGroupID(v int64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateGroupID() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldGroupID)
	return u
}

// SetBalanceRateMultiplier sets the "balance_rate_multiplier" field.
func (u *BillingProfileUpsert) SetBalanceRateMultiplier(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldBalanceRateMultiplier, v)
	return u
}

// UpdateBalanceRateMultiplier sets the "balance_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateBalanceRateMultiplier() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldBalanceRateMultiplier)
	return u
}

// AddBalanceRateMultiplier adds v to the "balance_rate_multiplier" field.
func (u *BillingProfileUpsert) AddBalanceRateMultiplier(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldBalanceRateMultiplier, v)
	return u
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (u *BillingProfileUpsert) SetPeakRateEnabled(v bool) *BillingProfileUpsert {
	u.Set(billingprofile.FieldPeakRateEnabled, v)
	return u
}

// UpdatePeakRateEnabled sets the "peak_rate_enabled" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdatePeakRateEnabled() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldPeakRateEnabled)
	return u
}

// SetPeakStart sets the "peak_start" field.
func (u *BillingProfileUpsert) SetPeakStart(v string) *BillingProfileUpsert {
	u.Set(billingprofile.FieldPeakStart, v)
	return u
}

// UpdatePeakStart sets the "peak_start" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdatePeakStart() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldPeakStart)
	return u
}

// SetPeakEnd sets the "peak_end" field.
func (u *BillingProfileUpsert) SetPeakEnd(v string) *BillingProfileUpsert {
	u.Set(billingprofile.FieldPeakEnd, v)
	return u
}

// UpdatePeakEnd sets the "peak_end" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdatePeakEnd() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldPeakEnd)
	return u
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (u *BillingProfileUpsert) SetPeakRateMultiplier(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldPeakRateMultiplier, v)
	return u
}

// UpdatePeakRateMultiplier sets the "peak_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdatePeakRateMultiplier() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldPeakRateMultiplier)
	return u
}

// AddPeakRateMultiplier adds v to the "peak_rate_multiplier" field.
func (u *BillingProfileUpsert) AddPeakRateMultiplier(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldPeakRateMultiplier, v)
	return u
}

// SetImageRateIndependent sets the "image_rate_independent" field.
func (u *BillingProfileUpsert) SetImageRateIndependent(v bool) *BillingProfileUpsert {
	u.Set(billingprofile.FieldImageRateIndependent, v)
	return u
}

// UpdateImageRateIndependent sets the "image_rate_independent" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateImageRateIndependent() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldImageRateIndependent)
	return u
}

// SetImageRateMultiplier sets the "image_rate_multiplier" field.
func (u *BillingProfileUpsert) SetImageRateMultiplier(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldImageRateMultiplier, v)
	return u
}

// UpdateImageRateMultiplier sets the "image_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateImageRateMultiplier() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldImageRateMultiplier)
	return u
}

// AddImageRateMultiplier adds v to the "image_rate_multiplier" field.
func (u *BillingProfileUpsert) AddImageRateMultiplier(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldImageRateMultiplier, v)
	return u
}

// SetImagePrice1k sets the "image_price_1k" field.
func (u *BillingProfileUpsert) SetImagePrice1k(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldImagePrice1k, v)
	return u
}

// UpdateImagePrice1k sets the "image_price_1k" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateImagePrice1k() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldImagePrice1k)
	return u
}

// AddImagePrice1k adds v to the "image_price_1k" field.
func (u *BillingProfileUpsert) AddImagePrice1k(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldImagePrice1k, v)
	return u
}

// ClearImagePrice1k clears the value of the "image_price_1k" field.
func (u *BillingProfileUpsert) ClearImagePrice1k() *BillingProfileUpsert {
	u.SetNull(billingprofile.FieldImagePrice1k)
	return u
}

// SetImagePrice2k sets the "image_price_2k" field.
func (u *BillingProfileUpsert) SetImagePrice2k(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldImagePrice2k, v)
	return u
}

// UpdateImagePrice2k sets the "image_price_2k" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateImagePrice2k() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldImagePrice2k)
	return u
}

// AddImagePrice2k adds v to the "image_price_2k" field.
func (u *BillingProfileUpsert) AddImagePrice2k(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldImagePrice2k, v)
	return u
}

// ClearImagePrice2k clears the value of the "image_price_2k" field.
func (u *BillingProfileUpsert) ClearImagePrice2k() *BillingProfileUpsert {
	u.SetNull(billingprofile.FieldImagePrice2k)
	return u
}

// SetImagePrice4k sets the "image_price_4k" field.
func (u *BillingProfileUpsert) SetImagePrice4k(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldImagePrice4k, v)
	return u
}

// UpdateImagePrice4k sets the "image_price_4k" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateImagePrice4k() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldImagePrice4k)
	return u
}

// AddImagePrice4k adds v to the "image_price_4k" field.
func (u *BillingProfileUpsert) AddImagePrice4k(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldImagePrice4k, v)
	return u
}

// ClearImagePrice4k clears the value of the "image_price_4k" field.
func (u *BillingProfileUpsert) ClearImagePrice4k() *BillingProfileUpsert {
	u.SetNull(billingprofile.FieldImagePrice4k)
	return u
}

// SetBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field.
func (u *BillingProfileUpsert) SetBatchImageDiscountMultiplier(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldBatchImageDiscountMultiplier, v)
	return u
}

// UpdateBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateBatchImageDiscountMultiplier() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldBatchImageDiscountMultiplier)
	return u
}

// AddBatchImageDiscountMultiplier adds v to the "batch_image_discount_multiplier" field.
func (u *BillingProfileUpsert) AddBatchImageDiscountMultiplier(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldBatchImageDiscountMultiplier, v)
	return u
}

// SetBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field.
func (u *BillingProfileUpsert) SetBatchImageHoldMultiplier(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldBatchImageHoldMultiplier, v)
	return u
}

// UpdateBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateBatchImageHoldMultiplier() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldBatchImageHoldMultiplier)
	return u
}

// AddBatchImageHoldMultiplier adds v to the "batch_image_hold_multiplier" field.
func (u *BillingProfileUpsert) AddBatchImageHoldMultiplier(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldBatchImageHoldMultiplier, v)
	return u
}

// SetVideoRateIndependent sets the "video_rate_independent" field.
func (u *BillingProfileUpsert) SetVideoRateIndependent(v bool) *BillingProfileUpsert {
	u.Set(billingprofile.FieldVideoRateIndependent, v)
	return u
}

// UpdateVideoRateIndependent sets the "video_rate_independent" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateVideoRateIndependent() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldVideoRateIndependent)
	return u
}

// SetVideoRateMultiplier sets the "video_rate_multiplier" field.
func (u *BillingProfileUpsert) SetVideoRateMultiplier(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldVideoRateMultiplier, v)
	return u
}

// UpdateVideoRateMultiplier sets the "video_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateVideoRateMultiplier() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldVideoRateMultiplier)
	return u
}

// AddVideoRateMultiplier adds v to the "video_rate_multiplier" field.
func (u *BillingProfileUpsert) AddVideoRateMultiplier(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldVideoRateMultiplier, v)
	return u
}

// SetVideoPrice480p sets the "video_price_480p" field.
func (u *BillingProfileUpsert) SetVideoPrice480p(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldVideoPrice480p, v)
	return u
}

// UpdateVideoPrice480p sets the "video_price_480p" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateVideoPrice480p() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldVideoPrice480p)
	return u
}

// AddVideoPrice480p adds v to the "video_price_480p" field.
func (u *BillingProfileUpsert) AddVideoPrice480p(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldVideoPrice480p, v)
	return u
}

// ClearVideoPrice480p clears the value of the "video_price_480p" field.
func (u *BillingProfileUpsert) ClearVideoPrice480p() *BillingProfileUpsert {
	u.SetNull(billingprofile.FieldVideoPrice480p)
	return u
}

// SetVideoPrice720p sets the "video_price_720p" field.
func (u *BillingProfileUpsert) SetVideoPrice720p(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldVideoPrice720p, v)
	return u
}

// UpdateVideoPrice720p sets the "video_price_720p" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateVideoPrice720p() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldVideoPrice720p)
	return u
}

// AddVideoPrice720p adds v to the "video_price_720p" field.
func (u *BillingProfileUpsert) AddVideoPrice720p(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldVideoPrice720p, v)
	return u
}

// ClearVideoPrice720p clears the value of the "video_price_720p" field.
func (u *BillingProfileUpsert) ClearVideoPrice720p() *BillingProfileUpsert {
	u.SetNull(billingprofile.FieldVideoPrice720p)
	return u
}

// SetVideoPrice1080p sets the "video_price_1080p" field.
func (u *BillingProfileUpsert) SetVideoPrice1080p(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldVideoPrice1080p, v)
	return u
}

// UpdateVideoPrice1080p sets the "video_price_1080p" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateVideoPrice1080p() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldVideoPrice1080p)
	return u
}

// AddVideoPrice1080p adds v to the "video_price_1080p" field.
func (u *BillingProfileUpsert) AddVideoPrice1080p(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldVideoPrice1080p, v)
	return u
}

// ClearVideoPrice1080p clears the value of the "video_price_1080p" field.
func (u *BillingProfileUpsert) ClearVideoPrice1080p() *BillingProfileUpsert {
	u.SetNull(billingprofile.FieldVideoPrice1080p)
	return u
}

// SetWebSearchPricePerCall sets the "web_search_price_per_call" field.
func (u *BillingProfileUpsert) SetWebSearchPricePerCall(v float64) *BillingProfileUpsert {
	u.Set(billingprofile.FieldWebSearchPricePerCall, v)
	return u
}

// UpdateWebSearchPricePerCall sets the "web_search_price_per_call" field to the value that was provided on create.
func (u *BillingProfileUpsert) UpdateWebSearchPricePerCall() *BillingProfileUpsert {
	u.SetExcluded(billingprofile.FieldWebSearchPricePerCall)
	return u
}

// AddWebSearchPricePerCall adds v to the "web_search_price_per_call" field.
func (u *BillingProfileUpsert) AddWebSearchPricePerCall(v float64) *BillingProfileUpsert {
	u.Add(billingprofile.FieldWebSearchPricePerCall, v)
	return u
}

// ClearWebSearchPricePerCall clears the value of the "web_search_price_per_call" field.
func (u *BillingProfileUpsert) ClearWebSearchPricePerCall() *BillingProfileUpsert {
	u.SetNull(billingprofile.FieldWebSearchPricePerCall)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BillingProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BillingProfileUpsertOne) UpdateNewValues() *BillingProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(billingprofile.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BillingProfileUpsertOne) Ignore() *BillingProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingProfileUpsertOne) DoNothing() *BillingProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingProfileCreate.OnConflict
// documentation for more info.
func (u *BillingProfileUpsertOne) Update(set func(*BillingProfileUpsert)) *BillingProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingProfileUpsertOne) SetUpdatedAt(v time.Time) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateUpdatedAt() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BillingProfileUpsertOne) SetGroupID(v int64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateGroupID() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateGroupID()
	})
}

// SetBalanceRateMultiplier sets the "balance_rate_multiplier" field.
func (u *BillingProfileUpsertOne) SetBalanceRateMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetBalanceRateMultiplier(v)
	})
}

// AddBalanceRateMultiplier adds v to the "balance_rate_multiplier" field.
func (u *BillingProfileUpsertOne) AddBalanceRateMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddBalanceRateMultiplier(v)
	})
}

// UpdateBalanceRateMultiplier sets the "balance_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateBalanceRateMultiplier() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateBalanceRateMultiplier()
	})
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (u *BillingProfileUpsertOne) SetPeakRateEnabled(v bool) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetPeakRateEnabled(v)
	})
}

// UpdatePeakRateEnabled sets the "peak_rate_enabled" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdatePeakRateEnabled() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdatePeakRateEnabled()
	})
}

// SetPeakStart sets the "peak_start" field.
func (u *BillingProfileUpsertOne) SetPeakStart(v string) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetPeakStart(v)
	})
}

// UpdatePeakStart sets the "peak_start" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdatePeakStart() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdatePeakStart()
	})
}

// SetPeakEnd sets the "peak_end" field.
func (u *BillingProfileUpsertOne) SetPeakEnd(v string) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetPeakEnd(v)
	})
}

// UpdatePeakEnd sets the "peak_end" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdatePeakEnd() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdatePeakEnd()
	})
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (u *BillingProfileUpsertOne) SetPeakRateMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetPeakRateMultiplier(v)
	})
}

// AddPeakRateMultiplier adds v to the "peak_rate_multiplier" field.
func (u *BillingProfileUpsertOne) AddPeakRateMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddPeakRateMultiplier(v)
	})
}

// UpdatePeakRateMultiplier sets the "peak_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdatePeakRateMultiplier() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdatePeakRateMultiplier()
	})
}

// SetImageRateIndependent sets the "image_rate_independent" field.
func (u *BillingProfileUpsertOne) SetImageRateIndependent(v bool) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImageRateIndependent(v)
	})
}

// UpdateImageRateIndependent sets the "image_rate_independent" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateImageRateIndependent() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImageRateIndependent()
	})
}

// SetImageRateMultiplier sets the "image_rate_multiplier" field.
func (u *BillingProfileUpsertOne) SetImageRateMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImageRateMultiplier(v)
	})
}

// AddImageRateMultiplier adds v to the "image_rate_multiplier" field.
func (u *BillingProfileUpsertOne) AddImageRateMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddImageRateMultiplier(v)
	})
}

// UpdateImageRateMultiplier sets the "image_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateImageRateMultiplier() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImageRateMultiplier()
	})
}

// SetImagePrice1k sets the "image_price_1k" field.
func (u *BillingProfileUpsertOne) SetImagePrice1k(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImagePrice1k(v)
	})
}

// AddImagePrice1k adds v to the "image_price_1k" field.
func (u *BillingProfileUpsertOne) AddImagePrice1k(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddImagePrice1k(v)
	})
}

// UpdateImagePrice1k sets the "image_price_1k" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateImagePrice1k() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImagePrice1k()
	})
}

// ClearImagePrice1k clears the value of the "image_price_1k" field.
func (u *BillingProfileUpsertOne) ClearImagePrice1k() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearImagePrice1k()
	})
}

// SetImagePrice2k sets the "image_price_2k" field.
func (u *BillingProfileUpsertOne) SetImagePrice2k(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImagePrice2k(v)
	})
}

// AddImagePrice2k adds v to the "image_price_2k" field.
func (u *BillingProfileUpsertOne) AddImagePrice2k(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddImagePrice2k(v)
	})
}

// UpdateImagePrice2k sets the "image_price_2k" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateImagePrice2k() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImagePrice2k()
	})
}

// ClearImagePrice2k clears the value of the "image_price_2k" field.
func (u *BillingProfileUpsertOne) ClearImagePrice2k() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearImagePrice2k()
	})
}

// SetImagePrice4k sets the "image_price_4k" field.
func (u *BillingProfileUpsertOne) SetImagePrice4k(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImagePrice4k(v)
	})
}

// AddImagePrice4k adds v to the "image_price_4k" field.
func (u *BillingProfileUpsertOne) AddImagePrice4k(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddImagePrice4k(v)
	})
}

// UpdateImagePrice4k sets the "image_price_4k" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateImagePrice4k() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImagePrice4k()
	})
}

// ClearImagePrice4k clears the value of the "image_price_4k" field.
func (u *BillingProfileUpsertOne) ClearImagePrice4k() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearImagePrice4k()
	})
}

// SetBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field.
func (u *BillingProfileUpsertOne) SetBatchImageDiscountMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetBatchImageDiscountMultiplier(v)
	})
}

// AddBatchImageDiscountMultiplier adds v to the "batch_image_discount_multiplier" field.
func (u *BillingProfileUpsertOne) AddBatchImageDiscountMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddBatchImageDiscountMultiplier(v)
	})
}

// UpdateBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateBatchImageDiscountMultiplier() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateBatchImageDiscountMultiplier()
	})
}

// SetBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field.
func (u *BillingProfileUpsertOne) SetBatchImageHoldMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetBatchImageHoldMultiplier(v)
	})
}

// AddBatchImageHoldMultiplier adds v to the "batch_image_hold_multiplier" field.
func (u *BillingProfileUpsertOne) AddBatchImageHoldMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddBatchImageHoldMultiplier(v)
	})
}

// UpdateBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateBatchImageHoldMultiplier() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateBatchImageHoldMultiplier()
	})
}

// SetVideoRateIndependent sets the "video_rate_independent" field.
func (u *BillingProfileUpsertOne) SetVideoRateIndependent(v bool) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoRateIndependent(v)
	})
}

// UpdateVideoRateIndependent sets the "video_rate_independent" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateVideoRateIndependent() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoRateIndependent()
	})
}

// SetVideoRateMultiplier sets the "video_rate_multiplier" field.
func (u *BillingProfileUpsertOne) SetVideoRateMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoRateMultiplier(v)
	})
}

// AddVideoRateMultiplier adds v to the "video_rate_multiplier" field.
func (u *BillingProfileUpsertOne) AddVideoRateMultiplier(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddVideoRateMultiplier(v)
	})
}

// UpdateVideoRateMultiplier sets the "video_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateVideoRateMultiplier() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoRateMultiplier()
	})
}

// SetVideoPrice480p sets the "video_price_480p" field.
func (u *BillingProfileUpsertOne) SetVideoPrice480p(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoPrice480p(v)
	})
}

// AddVideoPrice480p adds v to the "video_price_480p" field.
func (u *BillingProfileUpsertOne) AddVideoPrice480p(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddVideoPrice480p(v)
	})
}

// UpdateVideoPrice480p sets the "video_price_480p" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateVideoPrice480p() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoPrice480p()
	})
}

// ClearVideoPrice480p clears the value of the "video_price_480p" field.
func (u *BillingProfileUpsertOne) ClearVideoPrice480p() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearVideoPrice480p()
	})
}

// SetVideoPrice720p sets the "video_price_720p" field.
func (u *BillingProfileUpsertOne) SetVideoPrice720p(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoPrice720p(v)
	})
}

// AddVideoPrice720p adds v to the "video_price_720p" field.
func (u *BillingProfileUpsertOne) AddVideoPrice720p(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddVideoPrice720p(v)
	})
}

// UpdateVideoPrice720p sets the "video_price_720p" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateVideoPrice720p() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoPrice720p()
	})
}

// ClearVideoPrice720p clears the value of the "video_price_720p" field.
func (u *BillingProfileUpsertOne) ClearVideoPrice720p() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearVideoPrice720p()
	})
}

// SetVideoPrice1080p sets the "video_price_1080p" field.
func (u *BillingProfileUpsertOne) SetVideoPrice1080p(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoPrice1080p(v)
	})
}

// AddVideoPrice1080p adds v to the "video_price_1080p" field.
func (u *BillingProfileUpsertOne) AddVideoPrice1080p(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddVideoPrice1080p(v)
	})
}

// UpdateVideoPrice1080p sets the "video_price_1080p" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateVideoPrice1080p() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoPrice1080p()
	})
}

// ClearVideoPrice1080p clears the value of the "video_price_1080p" field.
func (u *BillingProfileUpsertOne) ClearVideoPrice1080p() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearVideoPrice1080p()
	})
}

// SetWebSearchPricePerCall sets the "web_search_price_per_call" field.
func (u *BillingProfileUpsertOne) SetWebSearchPricePerCall(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetWebSearchPricePerCall(v)
	})
}

// AddWebSearchPricePerCall adds v to the "web_search_price_per_call" field.
func (u *BillingProfileUpsertOne) AddWebSearchPricePerCall(v float64) *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddWebSearchPricePerCall(v)
	})
}

// UpdateWebSearchPricePerCall sets the "web_search_price_per_call" field to the value that was provided on create.
func (u *BillingProfileUpsertOne) UpdateWebSearchPricePerCall() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateWebSearchPricePerCall()
	})
}

// ClearWebSearchPricePerCall clears the value of the "web_search_price_per_call" field.
func (u *BillingProfileUpsertOne) ClearWebSearchPricePerCall() *BillingProfileUpsertOne {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearWebSearchPricePerCall()
	})
}

// Exec executes the query.
func (u *BillingProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BillingProfileUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BillingProfileUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BillingProfileCreateBulk is the builder for creating many BillingProfile entities in bulk.
type BillingProfileCreateBulk struct {
	config
	err      error
	builders []*BillingProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the BillingProfile entities in the database.
func (_c *BillingProfileCreateBulk) Save(ctx context.Context) ([]*BillingProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BillingProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillingProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillingProfileCreateBulk) SaveX(ctx context.Context) []*BillingProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *BillingProfileUpsertBulk {
	_c.conflict = opts
	return &BillingProfileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingProfileCreateBulk) OnConflictColumns(columns ...string) *BillingProfileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingProfileUpsertBulk{
		create: _c,
	}
}

// BillingProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of BillingProfile nodes.
type BillingProfileUpsertBulk struct {
	create *BillingProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BillingProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BillingProfileUpsertBulk) UpdateNewValues() *BillingProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(billingprofile.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BillingProfileUpsertBulk) Ignore() *BillingProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingProfileUpsertBulk) DoNothing() *BillingProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingProfileCreateBulk.OnConflict
// documentation for more info.
func (u *BillingProfileUpsertBulk) Update(set func(*BillingProfileUpsert)) *BillingProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingProfileUpsertBulk) SetUpdatedAt(v time.Time) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateUpdatedAt() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BillingProfileUpsertBulk) SetGroupID(v int64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateGroupID() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateGroupID()
	})
}

// SetBalanceRateMultiplier sets the "balance_rate_multiplier" field.
func (u *BillingProfileUpsertBulk) SetBalanceRateMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetBalanceRateMultiplier(v)
	})
}

// AddBalanceRateMultiplier adds v to the "balance_rate_multiplier" field.
func (u *BillingProfileUpsertBulk) AddBalanceRateMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddBalanceRateMultiplier(v)
	})
}

// UpdateBalanceRateMultiplier sets the "balance_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateBalanceRateMultiplier() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateBalanceRateMultiplier()
	})
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (u *BillingProfileUpsertBulk) SetPeakRateEnabled(v bool) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetPeakRateEnabled(v)
	})
}

// UpdatePeakRateEnabled sets the "peak_rate_enabled" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdatePeakRateEnabled() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdatePeakRateEnabled()
	})
}

// SetPeakStart sets the "peak_start" field.
func (u *BillingProfileUpsertBulk) SetPeakStart(v string) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetPeakStart(v)
	})
}

// UpdatePeakStart sets the "peak_start" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdatePeakStart() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdatePeakStart()
	})
}

// SetPeakEnd sets the "peak_end" field.
func (u *BillingProfileUpsertBulk) SetPeakEnd(v string) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetPeakEnd(v)
	})
}

// UpdatePeakEnd sets the "peak_end" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdatePeakEnd() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdatePeakEnd()
	})
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (u *BillingProfileUpsertBulk) SetPeakRateMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetPeakRateMultiplier(v)
	})
}

// AddPeakRateMultiplier adds v to the "peak_rate_multiplier" field.
func (u *BillingProfileUpsertBulk) AddPeakRateMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddPeakRateMultiplier(v)
	})
}

// UpdatePeakRateMultiplier sets the "peak_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdatePeakRateMultiplier() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdatePeakRateMultiplier()
	})
}

// SetImageRateIndependent sets the "image_rate_independent" field.
func (u *BillingProfileUpsertBulk) SetImageRateIndependent(v bool) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImageRateIndependent(v)
	})
}

// UpdateImageRateIndependent sets the "image_rate_independent" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateImageRateIndependent() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImageRateIndependent()
	})
}

// SetImageRateMultiplier sets the "image_rate_multiplier" field.
func (u *BillingProfileUpsertBulk) SetImageRateMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImageRateMultiplier(v)
	})
}

// AddImageRateMultiplier adds v to the "image_rate_multiplier" field.
func (u *BillingProfileUpsertBulk) AddImageRateMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddImageRateMultiplier(v)
	})
}

// UpdateImageRateMultiplier sets the "image_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateImageRateMultiplier() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImageRateMultiplier()
	})
}

// SetImagePrice1k sets the "image_price_1k" field.
func (u *BillingProfileUpsertBulk) SetImagePrice1k(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImagePrice1k(v)
	})
}

// AddImagePrice1k adds v to the "image_price_1k" field.
func (u *BillingProfileUpsertBulk) AddImagePrice1k(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddImagePrice1k(v)
	})
}

// UpdateImagePrice1k sets the "image_price_1k" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateImagePrice1k() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImagePrice1k()
	})
}

// ClearImagePrice1k clears the value of the "image_price_1k" field.
func (u *BillingProfileUpsertBulk) ClearImagePrice1k() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearImagePrice1k()
	})
}

// SetImagePrice2k sets the "image_price_2k" field.
func (u *BillingProfileUpsertBulk) SetImagePrice2k(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImagePrice2k(v)
	})
}

// AddImagePrice2k adds v to the "image_price_2k" field.
func (u *BillingProfileUpsertBulk) AddImagePrice2k(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddImagePrice2k(v)
	})
}

// UpdateImagePrice2k sets the "image_price_2k" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateImagePrice2k() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImagePrice2k()
	})
}

// ClearImagePrice2k clears the value of the "image_price_2k" field.
func (u *BillingProfileUpsertBulk) ClearImagePrice2k() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearImagePrice2k()
	})
}

// SetImagePrice4k sets the "image_price_4k" field.
func (u *BillingProfileUpsertBulk) SetImagePrice4k(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetImagePrice4k(v)
	})
}

// AddImagePrice4k adds v to the "image_price_4k" field.
func (u *BillingProfileUpsertBulk) AddImagePrice4k(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddImagePrice4k(v)
	})
}

// UpdateImagePrice4k sets the "image_price_4k" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateImagePrice4k() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateImagePrice4k()
	})
}

// ClearImagePrice4k clears the value of the "image_price_4k" field.
func (u *BillingProfileUpsertBulk) ClearImagePrice4k() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearImagePrice4k()
	})
}

// SetBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field.
func (u *BillingProfileUpsertBulk) SetBatchImageDiscountMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetBatchImageDiscountMultiplier(v)
	})
}

// AddBatchImageDiscountMultiplier adds v to the "batch_image_discount_multiplier" field.
func (u *BillingProfileUpsertBulk) AddBatchImageDiscountMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddBatchImageDiscountMultiplier(v)
	})
}

// UpdateBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateBatchImageDiscountMultiplier() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateBatchImageDiscountMultiplier()
	})
}

// SetBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field.
func (u *BillingProfileUpsertBulk) SetBatchImageHoldMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetBatchImageHoldMultiplier(v)
	})
}

// AddBatchImageHoldMultiplier adds v to the "batch_image_hold_multiplier" field.
func (u *BillingProfileUpsertBulk) AddBatchImageHoldMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddBatchImageHoldMultiplier(v)
	})
}

// UpdateBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateBatchImageHoldMultiplier() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateBatchImageHoldMultiplier()
	})
}

// SetVideoRateIndependent sets the "video_rate_independent" field.
func (u *BillingProfileUpsertBulk) SetVideoRateIndependent(v bool) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoRateIndependent(v)
	})
}

// UpdateVideoRateIndependent sets the "video_rate_independent" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateVideoRateIndependent() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoRateIndependent()
	})
}

// SetVideoRateMultiplier sets the "video_rate_multiplier" field.
func (u *BillingProfileUpsertBulk) SetVideoRateMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoRateMultiplier(v)
	})
}

// AddVideoRateMultiplier adds v to the "video_rate_multiplier" field.
func (u *BillingProfileUpsertBulk) AddVideoRateMultiplier(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddVideoRateMultiplier(v)
	})
}

// UpdateVideoRateMultiplier sets the "video_rate_multiplier" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateVideoRateMultiplier() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoRateMultiplier()
	})
}

// SetVideoPrice480p sets the "video_price_480p" field.
func (u *BillingProfileUpsertBulk) SetVideoPrice480p(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoPrice480p(v)
	})
}

// AddVideoPrice480p adds v to the "video_price_480p" field.
func (u *BillingProfileUpsertBulk) AddVideoPrice480p(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddVideoPrice480p(v)
	})
}

// UpdateVideoPrice480p sets the "video_price_480p" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateVideoPrice480p() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoPrice480p()
	})
}

// ClearVideoPrice480p clears the value of the "video_price_480p" field.
func (u *BillingProfileUpsertBulk) ClearVideoPrice480p() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearVideoPrice480p()
	})
}

// SetVideoPrice720p sets the "video_price_720p" field.
func (u *BillingProfileUpsertBulk) SetVideoPrice720p(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoPrice720p(v)
	})
}

// AddVideoPrice720p adds v to the "video_price_720p" field.
func (u *BillingProfileUpsertBulk) AddVideoPrice720p(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddVideoPrice720p(v)
	})
}

// UpdateVideoPrice720p sets the "video_price_720p" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateVideoPrice720p() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoPrice720p()
	})
}

// ClearVideoPrice720p clears the value of the "video_price_720p" field.
func (u *BillingProfileUpsertBulk) ClearVideoPrice720p() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearVideoPrice720p()
	})
}

// SetVideoPrice1080p sets the "video_price_1080p" field.
func (u *BillingProfileUpsertBulk) SetVideoPrice1080p(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetVideoPrice1080p(v)
	})
}

// AddVideoPrice1080p adds v to the "video_price_1080p" field.
func (u *BillingProfileUpsertBulk) AddVideoPrice1080p(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddVideoPrice1080p(v)
	})
}

// UpdateVideoPrice1080p sets the "video_price_1080p" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateVideoPrice1080p() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateVideoPrice1080p()
	})
}

// ClearVideoPrice1080p clears the value of the "video_price_1080p" field.
func (u *BillingProfileUpsertBulk) ClearVideoPrice1080p() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearVideoPrice1080p()
	})
}

// SetWebSearchPricePerCall sets the "web_search_price_per_call" field.
func (u *BillingProfileUpsertBulk) SetWebSearchPricePerCall(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.SetWebSearchPricePerCall(v)
	})
}

// AddWebSearchPricePerCall adds v to the "web_search_price_per_call" field.
func (u *BillingProfileUpsertBulk) AddWebSearchPricePerCall(v float64) *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.AddWebSearchPricePerCall(v)
	})
}

// UpdateWebSearchPricePerCall sets the "web_search_price_per_call" field to the value that was provided on create.
func (u *BillingProfileUpsertBulk) UpdateWebSearchPricePerCall() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.UpdateWebSearchPricePerCall()
	})
}

// ClearWebSearchPricePerCall clears the value of the "web_search_price_per_call" field.
func (u *BillingProfileUpsertBulk) ClearWebSearchPricePerCall() *BillingProfileUpsertBulk {
	return u.Update(func(s *BillingProfileUpsert) {
		s.ClearWebSearchPricePerCall()
	})
}

// Exec executes the query.
func (u *BillingProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BillingProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
