// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/billingprofile"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BillingProfileUpdate is the builder for updating BillingProfile entities.
type BillingProfileUpdate struct {
	config
	hooks    []Hook
	mutation *BillingProfileMutation
}

// Where appends a list predicates to the BillingProfileUpdate builder.
func (_u *BillingProfileUpdate) Where(ps ...predicate.BillingProfile) *BillingProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingProfileUpdate) SetUpdatedAt(v time.Time) *BillingProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BillingProfileUpdate) SetGroupID(v int64) *BillingProfileUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableGroupID(v *int64) *BillingProfileUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetBalanceRateMultiplier sets the "balance_rate_multiplier" field.
func (_u *BillingProfileUpdate) SetBalanceRateMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.ResetBalanceRateMultiplier()
	_u.mutation.SetBalanceRateMultiplier(v)
	return _u
}

// SetNillableBalanceRateMultiplier sets the "balance_rate_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableBalanceRateMultiplier(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetBalanceRateMultiplier(*v)
	}
	return _u
}

// AddBalanceRateMultiplier adds value to the "balance_rate_multiplier" field.
func (_u *BillingProfileUpdate) AddBalanceRateMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.AddBalanceRateMultiplier(v)
	return _u
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (_u *BillingProfileUpdate) SetPeakRateEnabled(v bool) *BillingProfileUpdate {
	_u.mutation.SetPeakRateEnabled(v)
	return _u
}

// SetNillablePeakRateEnabled sets the "peak_rate_enabled" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillablePeakRateEnabled(v *bool) *BillingProfileUpdate {
	if v != nil {
		_u.SetPeakRateEnabled(*v)
	}
	return _u
}

// SetPeakStart sets the "peak_start" field.
func (_u *BillingProfileUpdate) SetPeakStart(v string) *BillingProfileUpdate {
	_u.mutation.SetPeakStart(v)
	return _u
}

// SetNillablePeakStart sets the "peak_start" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillablePeakStart(v *string) *BillingProfileUpdate {
	if v != nil {
		_u.SetPeakStart(*v)
	}
	return _u
}

// SetPeakEnd sets the "peak_end" field.
func (_u *BillingProfileUpdate) SetPeakEnd(v string) *BillingProfileUpdate {
	_u.mutation.SetPeakEnd(v)
	return _u
}

// SetNillablePeakEnd sets the "peak_end" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillablePeakEnd(v *string) *BillingProfileUpdate {
	if v != nil {
		_u.SetPeakEnd(*v)
	}
	return _u
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (_u *BillingProfileUpdate) SetPeakRateMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.ResetPeakRateMultiplier()
	_u.mutation.SetPeakRateMultiplier(v)
	return _u
}

// SetNillablePeakRateMultiplier sets the "peak_rate_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillablePeakRateMultiplier(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetPeakRateMultiplier(*v)
	}
	return _u
}

// AddPeakRateMultiplier adds value to the "peak_rate_multiplier" field.
func (_u *BillingProfileUpdate) AddPeakRateMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.AddPeakRateMultiplier(v)
	return _u
}

// SetImageRateIndependent sets the "image_rate_independent" field.
func (_u *BillingProfileUpdate) SetImageRateIndependent(v bool) *BillingProfileUpdate {
	_u.mutation.SetImageRateIndependent(v)
	return _u
}

// SetNillableImageRateIndependent sets the "image_rate_independent" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableImageRateIndependent(v *bool) *BillingProfileUpdate {
	if v != nil {
		_u.SetImageRateIndependent(*v)
	}
	return _u
}

// SetImageRateMultiplier sets the "image_rate_multiplier" field.
func (_u *BillingProfileUpdate) SetImageRateMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.ResetImageRateMultiplier()
	_u.mutation.SetImageRateMultiplier(v)
	return _u
}

// SetNillableImageRateMultiplier sets the "image_rate_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableImageRateMultiplier(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetImageRateMultiplier(*v)
	}
	return _u
}

// AddImageRateMultiplier adds value to the "image_rate_multiplier" field.
func (_u *BillingProfileUpdate) AddImageRateMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.AddImageRateMultiplier(v)
	return _u
}

// SetImagePrice1k sets the "image_price_1k" field.
func (_u *BillingProfileUpdate) SetImagePrice1k(v float64) *BillingProfileUpdate {
	_u.mutation.ResetImagePrice1k()
	_u.mutation.SetImagePrice1k(v)
	return _u
}

// SetNillableImagePrice1k sets the "image_price_1k" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableImagePrice1k(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetImagePrice1k(*v)
	}
	return _u
}

// AddImagePrice1k adds value to the "image_price_1k" field.
func (_u *BillingProfileUpdate) AddImagePrice1k(v float64) *BillingProfileUpdate {
	_u.mutation.AddImagePrice1k(v)
	return _u
}

// ClearImagePrice1k clears the value of the "image_price_1k" field.
func (_u *BillingProfileUpdate) ClearImagePrice1k() *BillingProfileUpdate {
	_u.mutation.ClearImagePrice1k()
	return _u
}

// SetImagePrice2k sets the "image_price_2k" field.
func (_u *BillingProfileUpdate) SetImagePrice2k(v float64) *BillingProfileUpdate {
	_u.mutation.ResetImagePrice2k()
	_u.mutation.SetImagePrice2k(v)
	return _u
}

// SetNillableImagePrice2k sets the "image_price_2k" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableImagePrice2k(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetImagePrice2k(*v)
	}
	return _u
}

// AddImagePrice2k adds value to the "image_price_2k" field.
func (_u *BillingProfileUpdate) AddImagePrice2k(v float64) *BillingProfileUpdate {
	_u.mutation.AddImagePrice2k(v)
	return _u
}

// ClearImagePrice2k clears the value of the "image_price_2k" field.
func (_u *BillingProfileUpdate) ClearImagePrice2k() *BillingProfileUpdate {
	_u.mutation.ClearImagePrice2k()
	return _u
}

// SetImagePrice4k sets the "image_price_4k" field.
func (_u *BillingProfileUpdate) SetImagePrice4k(v float64) *BillingProfileUpdate {
	_u.mutation.ResetImagePrice4k()
	_u.mutation.SetImagePrice4k(v)
	return _u
}

// SetNillableImagePrice4k sets the "image_price_4k" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableImagePrice4k(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetImagePrice4k(*v)
	}
	return _u
}

// AddImagePrice4k adds value to the "image_price_4k" field.
func (_u *BillingProfileUpdate) AddImagePrice4k(v float64) *BillingProfileUpdate {
	_u.mutation.AddImagePrice4k(v)
	return _u
}

// ClearImagePrice4k clears the value of the "image_price_4k" field.
func (_u *BillingProfileUpdate) ClearImagePrice4k() *BillingProfileUpdate {
	_u.mutation.ClearImagePrice4k()
	return _u
}

// SetBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field.
func (_u *BillingProfileUpdate) SetBatchImageDiscountMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.ResetBatchImageDiscountMultiplier()
	_u.mutation.SetBatchImageDiscountMultiplier(v)
	return _u
}

// SetNillableBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableBatchImageDiscountMultiplier(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetBatchImageDiscountMultiplier(*v)
	}
	return _u
}

// AddBatchImageDiscountMultiplier adds value to the "batch_image_discount_multiplier" field.
func (_u *BillingProfileUpdate) AddBatchImageDiscountMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.AddBatchImageDiscountMultiplier(v)
	return _u
}

// SetBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field.
func (_u *BillingProfileUpdate) SetBatchImageHoldMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.ResetBatchImageHoldMultiplier()
	_u.mutation.SetBatchImageHoldMultiplier(v)
	return _u
}

// SetNillableBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableBatchImageHoldMultiplier(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetBatchImageHoldMultiplier(*v)
	}
	return _u
}

// AddBatchImageHoldMultiplier adds value to the "batch_image_hold_multiplier" field.
func (_u *BillingProfileUpdate) AddBatchImageHoldMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.AddBatchImageHoldMultiplier(v)
	return _u
}

// SetVideoRateIndependent sets the "video_rate_independent" field.
func (_u *BillingProfileUpdate) SetVideoRateIndependent(v bool) *BillingProfileUpdate {
	_u.mutation.SetVideoRateIndependent(v)
	return _u
}

// SetNillableVideoRateIndependent sets the "video_rate_independent" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableVideoRateIndependent(v *bool) *BillingProfileUpdate {
	if v != nil {
		_u.SetVideoRateIndependent(*v)
	}
	return _u
}

// SetVideoRateMultiplier sets the "video_rate_multiplier" field.
func (_u *BillingProfileUpdate) SetVideoRateMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.ResetVideoRateMultiplier()
	_u.mutation.SetVideoRateMultiplier(v)
	return _u
}

// SetNillableVideoRateMultiplier sets the "video_rate_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableVideoRateMultiplier(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetVideoRateMultiplier(*v)
	}
	return _u
}

// AddVideoRateMultiplier adds value to the "video_rate_multiplier" field.
func (_u *BillingProfileUpdate) AddVideoRateMultiplier(v float64) *BillingProfileUpdate {
	_u.mutation.AddVideoRateMultiplier(v)
	return _u
}

// SetVideoPrice480p sets the "video_price_480p" field.
func (_u *BillingProfileUpdate) SetVideoPrice480p(v float64) *BillingProfileUpdate {
	_u.mutation.ResetVideoPrice480p()
	_u.mutation.SetVideoPrice480p(v)
	return _u
}

// SetNillableVideoPrice480p sets the "video_price_480p" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableVideoPrice480p(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetVideoPrice480p(*v)
	}
	return _u
}

// AddVideoPrice480p adds value to the "video_price_480p" field.
func (_u *BillingProfileUpdate) AddVideoPrice480p(v float64) *BillingProfileUpdate {
	_u.mutation.AddVideoPrice480p(v)
	return _u
}

// ClearVideoPrice480p clears the value of the "video_price_480p" field.
func (_u *BillingProfileUpdate) ClearVideoPrice480p() *BillingProfileUpdate {
	_u.mutation.ClearVideoPrice480p()
	return _u
}

// SetVideoPrice720p sets the "video_price_720p" field.
func (_u *BillingProfileUpdate) SetVideoPrice720p(v float64) *BillingProfileUpdate {
	_u.mutation.ResetVideoPrice720p()
	_u.mutation.SetVideoPrice720p(v)
	return _u
}

// SetNillableVideoPrice720p sets the "video_price_720p" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableVideoPrice720p(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetVideoPrice720p(*v)
	}
	return _u
}

// AddVideoPrice720p adds value to the "video_price_720p" field.
func (_u *BillingProfileUpdate) AddVideoPrice720p(v float64) *BillingProfileUpdate {
	_u.mutation.AddVideoPrice720p(v)
	return _u
}

// ClearVideoPrice720p clears the value of the "video_price_720p" field.
func (_u *BillingProfileUpdate) ClearVideoPrice720p() *BillingProfileUpdate {
	_u.mutation.ClearVideoPrice720p()
	return _u
}

// SetVideoPrice1080p sets the "video_price_1080p" field.
func (_u *BillingProfileUpdate) SetVideoPrice1080p(v float64) *BillingProfileUpdate {
	_u.mutation.ResetVideoPrice1080p()
	_u.mutation.SetVideoPrice1080p(v)
	return _u
}

// SetNillableVideoPrice1080p sets the "video_price_1080p" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableVideoPrice1080p(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetVideoPrice1080p(*v)
	}
	return _u
}

// AddVideoPrice1080p adds value to the "video_price_1080p" field.
func (_u *BillingProfileUpdate) AddVideoPrice1080p(v float64) *BillingProfileUpdate {
	_u.mutation.AddVideoPrice1080p(v)
	return _u
}

// ClearVideoPrice1080p clears the value of the "video_price_1080p" field.
func (_u *BillingProfileUpdate) ClearVideoPrice1080p() *BillingProfileUpdate {
	_u.mutation.ClearVideoPrice1080p()
	return _u
}

// SetWebSearchPricePerCall sets the "web_search_price_per_call" field.
func (_u *BillingProfileUpdate) SetWebSearchPricePerCall(v float64) *BillingProfileUpdate {
	_u.mutation.ResetWebSearchPricePerCall()
	_u.mutation.SetWebSearchPricePerCall(v)
	return _u
}

// SetNillableWebSearchPricePerCall sets the "web_search_price_per_call" field if the given value is not nil.
func (_u *BillingProfileUpdate) SetNillableWebSearchPricePerCall(v *float64) *BillingProfileUpdate {
	if v != nil {
		_u.SetWebSearchPricePerCall(*v)
	}
	return _u
}

// AddWebSearchPricePerCall adds value to the "web_search_price_per_call" field.
func (_u *BillingProfileUpdate) AddWebSearchPricePerCall(v float64) *BillingProfileUpdate {
	_u.mutation.AddWebSearchPricePerCall(v)
	return _u
}

// ClearWebSearchPricePerCall clears the value of the "web_search_price_per_call" field.
func (_u *BillingProfileUpdate) ClearWebSearchPricePerCall() *BillingProfileUpdate {
	_u.mutation.ClearWebSearchPricePerCall()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BillingProfileUpdate) SetGroup(v *Group) *BillingProfileUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the BillingProfileMutation object of the builder.
func (_u *BillingProfileUpdate) Mutation() *BillingProfileMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BillingProfileUpdate) ClearGroup() *BillingProfileUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BillingProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BillingProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := billingprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillingProfileUpdate) check() error {
	if v, ok := _u.mutation.PeakStart(); ok {
		if err := billingprofile.PeakStartValidator(v); err != nil {
			return &ValidationError{Name: "peak_start", err: fmt.Errorf(`ent: validator failed for field "BillingProfile.peak_start": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeakEnd(); ok {
		if err := billingprofile.PeakEndValidator(v); err != nil {
			return &ValidationError{Name: "peak_end", err: fmt.Errorf(`ent: validator failed for field "BillingProfile.peak_end": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BillingProfile.group"`)
	}
	return nil
}

func (_u *BillingProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billingprofile.Table, billingprofile.Columns, sqlgraph.NewFieldSpec(billingprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BalanceRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBalanceRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceRateMultiplier(); ok {
		_spec.AddField(billingprofile.FieldBalanceRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PeakRateEnabled(); ok {
		_spec.SetField(billingprofile.FieldPeakRateEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PeakStart(); ok {
		_spec.SetField(billingprofile.FieldPeakStart, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeakEnd(); ok {
		_spec.SetField(billingprofile.FieldPeakEnd, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeakRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldPeakRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPeakRateMultiplier(); ok {
		_spec.AddField(billingprofile.FieldPeakRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ImageRateIndependent(); ok {
		_spec.SetField(billingprofile.FieldImageRateIndependent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ImageRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldImageRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageRateMultiplier(); ok {
		_spec.AddField(billingprofile.FieldImageRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ImagePrice1k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice1k, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImagePrice1k(); ok {
		_spec.AddField(billingprofile.FieldImagePrice1k, field.TypeFloat64, value)
	}
	if _u.mutation.ImagePrice1kCleared() {
		_spec.ClearField(billingprofile.FieldImagePrice1k, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImagePrice2k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice2k, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImagePrice2k(); ok {
		_spec.AddField(billingprofile.FieldImagePrice2k, field.TypeFloat64, value)
	}
	if _u.mutation.ImagePrice2kCleared() {
		_spec.ClearField(billingprofile.FieldImagePrice2k, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImagePrice4k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice4k, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImagePrice4k(); ok {
		_spec.AddField(billingprofile.FieldImagePrice4k, field.TypeFloat64, value)
	}
	if _u.mutation.ImagePrice4kCleared() {
		_spec.ClearField(billingprofile.FieldImagePrice4k, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BatchImageDiscountMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBatchImageDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBatchImageDiscountMultiplier(); ok {
		_spec.AddField(billingprofile.FieldBatchImageDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BatchImageHoldMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBatchImageHoldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBatchImageHoldMultiplier(); ok {
		_spec.AddField(billingprofile.FieldBatchImageHoldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.VideoRateIndependent(); ok {
		_spec.SetField(billingprofile.FieldVideoRateIndependent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VideoRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldVideoRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVideoRateMultiplier(); ok {
		_spec.AddField(billingprofile.FieldVideoRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.VideoPrice480p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice480p, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVideoPrice480p(); ok {
		_spec.AddField(billingprofile.FieldVideoPrice480p, field.TypeFloat64, value)
	}
	if _u.mutation.VideoPrice480pCleared() {
		_spec.ClearField(billingprofile.FieldVideoPrice480p, field.TypeFloat64)
	}
	if value, ok := _u.mutation.VideoPrice720p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice720p, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVideoPrice720p(); ok {
		_spec.AddField(billingprofile.FieldVideoPrice720p, field.TypeFloat64, value)
	}
	if _u.mutation.VideoPrice720pCleared() {
		_spec.ClearField(billingprofile.FieldVideoPrice720p, field.TypeFloat64)
	}
	if value, ok := _u.mutation.VideoPrice1080p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice1080p, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVideoPrice1080p(); ok {
		_spec.AddField(billingprofile.FieldVideoPrice1080p, field.TypeFloat64, value)
	}
	if _u.mutation.VideoPrice1080pCleared() {
		_spec.ClearField(billingprofile.FieldVideoPrice1080p, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WebSearchPricePerCall(); ok {
		_spec.SetField(billingprofile.FieldWebSearchPricePerCall, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWebSearchPricePerCall(); ok {
		_spec.AddField(billingprofile.FieldWebSearchPricePerCall, field.TypeFloat64, value)
	}
	if _u.mutation.WebSearchPricePerCallCleared() {
		_spec.ClearField(billingprofile.FieldWebSearchPricePerCall, field.TypeFloat64)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   billingprofile.GroupTable,
			Columns: []string{billingprofile.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   billingprofile.GroupTable,
			Columns: []string{billingprofile.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BillingProfileUpdateOne is the builder for updating a single BillingProfile entity.
type BillingProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BillingProfileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingProfileUpdateOne) SetUpdatedAt(v time.Time) *BillingProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BillingProfileUpdateOne) SetGroupID(v int64) *BillingProfileUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableGroupID(v *int64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetBalanceRateMultiplier sets the "balance_rate_multiplier" field.
func (_u *BillingProfileUpdateOne) SetBalanceRateMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetBalanceRateMultiplier()
	_u.mutation.SetBalanceRateMultiplier(v)
	return _u
}

// SetNillableBalanceRateMultiplier sets the "balance_rate_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableBalanceRateMultiplier(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetBalanceRateMultiplier(*v)
	}
	return _u
}

// AddBalanceRateMultiplier adds value to the "balance_rate_multiplier" field.
func (_u *BillingProfileUpdateOne) AddBalanceRateMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddBalanceRateMultiplier(v)
	return _u
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (_u *BillingProfileUpdateOne) SetPeakRateEnabled(v bool) *BillingProfileUpdateOne {
	_u.mutation.SetPeakRateEnabled(v)
	return _u
}

// SetNillablePeakRateEnabled sets the "peak_rate_enabled" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillablePeakRateEnabled(v *bool) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetPeakRateEnabled(*v)
	}
	return _u
}

// SetPeakStart sets the "peak_start" field.
func (_u *BillingProfileUpdateOne) SetPeakStart(v string) *BillingProfileUpdateOne {
	_u.mutation.SetPeakStart(v)
	return _u
}

// SetNillablePeakStart sets the "peak_start" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillablePeakStart(v *string) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetPeakStart(*v)
	}
	return _u
}

// SetPeakEnd sets the "peak_end" field.
func (_u *BillingProfileUpdateOne) SetPeakEnd(v string) *BillingProfileUpdateOne {
	_u.mutation.SetPeakEnd(v)
	return _u
}

// SetNillablePeakEnd sets the "peak_end" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillablePeakEnd(v *string) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetPeakEnd(*v)
	}
	return _u
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (_u *BillingProfileUpdateOne) SetPeakRateMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetPeakRateMultiplier()
	_u.mutation.SetPeakRateMultiplier(v)
	return _u
}

// SetNillablePeakRateMultiplier sets the "peak_rate_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillablePeakRateMultiplier(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetPeakRateMultiplier(*v)
	}
	return _u
}

// AddPeakRateMultiplier adds value to the "peak_rate_multiplier" field.
func (_u *BillingProfileUpdateOne) AddPeakRateMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddPeakRateMultiplier(v)
	return _u
}

// SetImageRateIndependent sets the "image_rate_independent" field.
func (_u *BillingProfileUpdateOne) SetImageRateIndependent(v bool) *BillingProfileUpdateOne {
	_u.mutation.SetImageRateIndependent(v)
	return _u
}

// SetNillableImageRateIndependent sets the "image_rate_independent" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableImageRateIndependent(v *bool) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetImageRateIndependent(*v)
	}
	return _u
}

// SetImageRateMultiplier sets the "image_rate_multiplier" field.
func (_u *BillingProfileUpdateOne) SetImageRateMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetImageRateMultiplier()
	_u.mutation.SetImageRateMultiplier(v)
	return _u
}

// SetNillableImageRateMultiplier sets the "image_rate_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableImageRateMultiplier(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetImageRateMultiplier(*v)
	}
	return _u
}

// AddImageRateMultiplier adds value to the "image_rate_multiplier" field.
func (_u *BillingProfileUpdateOne) AddImageRateMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddImageRateMultiplier(v)
	return _u
}

// SetImagePrice1k sets the "image_price_1k" field.
func (_u *BillingProfileUpdateOne) SetImagePrice1k(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetImagePrice1k()
	_u.mutation.SetImagePrice1k(v)
	return _u
}

// SetNillableImagePrice1k sets the "image_price_1k" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableImagePrice1k(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetImagePrice1k(*v)
	}
	return _u
}

// AddImagePrice1k adds value to the "image_price_1k" field.
func (_u *BillingProfileUpdateOne) AddImagePrice1k(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddImagePrice1k(v)
	return _u
}

// ClearImagePrice1k clears the value of the "image_price_1k" field.
func (_u *BillingProfileUpdateOne) ClearImagePrice1k() *BillingProfileUpdateOne {
	_u.mutation.ClearImagePrice1k()
	return _u
}

// SetImagePrice2k sets the "image_price_2k" field.
func (_u *BillingProfileUpdateOne) SetImagePrice2k(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetImagePrice2k()
	_u.mutation.SetImagePrice2k(v)
	return _u
}

// SetNillableImagePrice2k sets the "image_price_2k" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableImagePrice2k(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetImagePrice2k(*v)
	}
	return _u
}

// AddImagePrice2k adds value to the "image_price_2k" field.
func (_u *BillingProfileUpdateOne) AddImagePrice2k(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddImagePrice2k(v)
	return _u
}

// ClearImagePrice2k clears the value of the "image_price_2k" field.
func (_u *BillingProfileUpdateOne) ClearImagePrice2k() *BillingProfileUpdateOne {
	_u.mutation.ClearImagePrice2k()
	return _u
}

// SetImagePrice4k sets the "image_price_4k" field.
func (_u *BillingProfileUpdateOne) SetImagePrice4k(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetImagePrice4k()
	_u.mutation.SetImagePrice4k(v)
	return _u
}

// SetNillableImagePrice4k sets the "image_price_4k" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableImagePrice4k(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetImagePrice4k(*v)
	}
	return _u
}

// AddImagePrice4k adds value to the "image_price_4k" field.
func (_u *BillingProfileUpdateOne) AddImagePrice4k(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddImagePrice4k(v)
	return _u
}

// ClearImagePrice4k clears the value of the "image_price_4k" field.
func (_u *BillingProfileUpdateOne) ClearImagePrice4k() *BillingProfileUpdateOne {
	_u.mutation.ClearImagePrice4k()
	return _u
}

// SetBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field.
func (_u *BillingProfileUpdateOne) SetBatchImageDiscountMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetBatchImageDiscountMultiplier()
	_u.mutation.SetBatchImageDiscountMultiplier(v)
	return _u
}

// SetNillableBatchImageDiscountMultiplier sets the "batch_image_discount_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableBatchImageDiscountMultiplier(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetBatchImageDiscountMultiplier(*v)
	}
	return _u
}

// AddBatchImageDiscountMultiplier adds value to the "batch_image_discount_multiplier" field.
func (_u *BillingProfileUpdateOne) AddBatchImageDiscountMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddBatchImageDiscountMultiplier(v)
	return _u
}

// SetBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field.
func (_u *BillingProfileUpdateOne) SetBatchImageHoldMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetBatchImageHoldMultiplier()
	_u.mutation.SetBatchImageHoldMultiplier(v)
	return _u
}

// SetNillableBatchImageHoldMultiplier sets the "batch_image_hold_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableBatchImageHoldMultiplier(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetBatchImageHoldMultiplier(*v)
	}
	return _u
}

// AddBatchImageHoldMultiplier adds value to the "batch_image_hold_multiplier" field.
func (_u *BillingProfileUpdateOne) AddBatchImageHoldMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddBatchImageHoldMultiplier(v)
	return _u
}

// SetVideoRateIndependent sets the "video_rate_independent" field.
func (_u *BillingProfileUpdateOne) SetVideoRateIndependent(v bool) *BillingProfileUpdateOne {
	_u.mutation.SetVideoRateIndependent(v)
	return _u
}

// SetNillableVideoRateIndependent sets the "video_rate_independent" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableVideoRateIndependent(v *bool) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetVideoRateIndependent(*v)
	}
	return _u
}

// SetVideoRateMultiplier sets the "video_rate_multiplier" field.
func (_u *BillingProfileUpdateOne) SetVideoRateMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetVideoRateMultiplier()
	_u.mutation.SetVideoRateMultiplier(v)
	return _u
}

// SetNillableVideoRateMultiplier sets the "video_rate_multiplier" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableVideoRateMultiplier(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetVideoRateMultiplier(*v)
	}
	return _u
}

// AddVideoRateMultiplier adds value to the "video_rate_multiplier" field.
func (_u *BillingProfileUpdateOne) AddVideoRateMultiplier(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddVideoRateMultiplier(v)
	return _u
}

// SetVideoPrice480p sets the "video_price_480p" field.
func (_u *BillingProfileUpdateOne) SetVideoPrice480p(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetVideoPrice480p()
	_u.mutation.SetVideoPrice480p(v)
	return _u
}

// SetNillableVideoPrice480p sets the "video_price_480p" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableVideoPrice480p(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetVideoPrice480p(*v)
	}
	return _u
}

// AddVideoPrice480p adds value to the "video_price_480p" field.
func (_u *BillingProfileUpdateOne) AddVideoPrice480p(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddVideoPrice480p(v)
	return _u
}

// ClearVideoPrice480p clears the value of the "video_price_480p" field.
func (_u *BillingProfileUpdateOne) ClearVideoPrice480p() *BillingProfileUpdateOne {
	_u.mutation.ClearVideoPrice480p()
	return _u
}

// SetVideoPrice720p sets the "video_price_720p" field.
func (_u *BillingProfileUpdateOne) SetVideoPrice720p(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetVideoPrice720p()
	_u.mutation.SetVideoPrice720p(v)
	return _u
}

// SetNillableVideoPrice720p sets the "video_price_720p" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableVideoPrice720p(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetVideoPrice720p(*v)
	}
	return _u
}

// AddVideoPrice720p adds value to the "video_price_720p" field.
func (_u *BillingProfileUpdateOne) AddVideoPrice720p(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddVideoPrice720p(v)
	return _u
}

// ClearVideoPrice720p clears the value of the "video_price_720p" field.
func (_u *BillingProfileUpdateOne) ClearVideoPrice720p() *BillingProfileUpdateOne {
	_u.mutation.ClearVideoPrice720p()
	return _u
}

// SetVideoPrice1080p sets the "video_price_1080p" field.
func (_u *BillingProfileUpdateOne) SetVideoPrice1080p(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetVideoPrice1080p()
	_u.mutation.SetVideoPrice1080p(v)
	return _u
}

// SetNillableVideoPrice1080p sets the "video_price_1080p" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableVideoPrice1080p(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetVideoPrice1080p(*v)
	}
	return _u
}

// AddVideoPrice1080p adds value to the "video_price_1080p" field.
func (_u *BillingProfileUpdateOne) AddVideoPrice1080p(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddVideoPrice1080p(v)
	return _u
}

// ClearVideoPrice1080p clears the value of the "video_price_1080p" field.
func (_u *BillingProfileUpdateOne) ClearVideoPrice1080p() *BillingProfileUpdateOne {
	_u.mutation.ClearVideoPrice1080p()
	return _u
}

// SetWebSearchPricePerCall sets the "web_search_price_per_call" field.
func (_u *BillingProfileUpdateOne) SetWebSearchPricePerCall(v float64) *BillingProfileUpdateOne {
	_u.mutation.ResetWebSearchPricePerCall()
	_u.mutation.SetWebSearchPricePerCall(v)
	return _u
}

// SetNillableWebSearchPricePerCall sets the "web_search_price_per_call" field if the given value is not nil.
func (_u *BillingProfileUpdateOne) SetNillableWebSearchPricePerCall(v *float64) *BillingProfileUpdateOne {
	if v != nil {
		_u.SetWebSearchPricePerCall(*v)
	}
	return _u
}

// AddWebSearchPricePerCall adds value to the "web_search_price_per_call" field.
func (_u *BillingProfileUpdateOne) AddWebSearchPricePerCall(v float64) *BillingProfileUpdateOne {
	_u.mutation.AddWebSearchPricePerCall(v)
	return _u
}

// ClearWebSearchPricePerCall clears the value of the "web_search_price_per_call" field.
func (_u *BillingProfileUpdateOne) ClearWebSearchPricePerCall() *BillingProfileUpdateOne {
	_u.mutation.ClearWebSearchPricePerCall()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BillingProfileUpdateOne) SetGroup(v *Group) *BillingProfileUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the BillingProfileMutation object of the builder.
func (_u *BillingProfileUpdateOne) Mutation() *BillingProfileMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BillingProfileUpdateOne) ClearGroup() *BillingProfileUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the BillingProfileUpdate builder.
func (_u *BillingProfileUpdateOne) Where(ps ...predicate.BillingProfile) *BillingProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BillingProfileUpdateOne) Select(field string, fields ...string) *BillingProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BillingProfile entity.
func (_u *BillingProfileUpdateOne) Save(ctx context.Context) (*BillingProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingProfileUpdateOne) SaveX(ctx context.Context) *BillingProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BillingProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := billingprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillingProfileUpdateOne) check() error {
	if v, ok := _u.mutation.PeakStart(); ok {
		if err := billingprofile.PeakStartValidator(v); err != nil {
			return &ValidationError{Name: "peak_start", err: fmt.Errorf(`ent: validator failed for field "BillingProfile.peak_start": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeakEnd(); ok {
		if err := billingprofile.PeakEndValidator(v); err != nil {
			return &ValidationError{Name: "peak_end", err: fmt.Errorf(`ent: validator failed for field "BillingProfile.peak_end": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BillingProfile.group"`)
	}
	return nil
}

func (_u *BillingProfileUpdateOne) sqlSave(ctx context.Context) (_node *BillingProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billingprofile.Table, billingprofile.Columns, sqlgraph.NewFieldSpec(billingprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BillingProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billingprofile.FieldID)
		for _, f := range fields {
			if !billingprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != billingprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BalanceRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBalanceRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceRateMultiplier(); ok {
		_spec.AddField(billingprofile.FieldBalanceRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PeakRateEnabled(); ok {
		_spec.SetField(billingprofile.FieldPeakRateEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PeakStart(); ok {
		_spec.SetField(billingprofile.FieldPeakStart, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeakEnd(); ok {
		_spec.SetField(billingprofile.FieldPeakEnd, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeakRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldPeakRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPeakRateMultiplier(); ok {
		_spec.AddField(billingprofile.FieldPeakRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ImageRateIndependent(); ok {
		_spec.SetField(billingprofile.FieldImageRateIndependent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ImageRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldImageRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageRateMultiplier(); ok {
		_spec.AddField(billingprofile.FieldImageRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ImagePrice1k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice1k, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImagePrice1k(); ok {
		_spec.AddField(billingprofile.FieldImagePrice1k, field.TypeFloat64, value)
	}
	if _u.mutation.ImagePrice1kCleared() {
		_spec.ClearField(billingprofile.FieldImagePrice1k, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImagePrice2k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice2k, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImagePrice2k(); ok {
		_spec.AddField(billingprofile.FieldImagePrice2k, field.TypeFloat64, value)
	}
	if _u.mutation.ImagePrice2kCleared() {
		_spec.ClearField(billingprofile.FieldImagePrice2k, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImagePrice4k(); ok {
		_spec.SetField(billingprofile.FieldImagePrice4k, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImagePrice4k(); ok {
		_spec.AddField(billingprofile.FieldImagePrice4k, field.TypeFloat64, value)
	}
	if _u.mutation.ImagePrice4kCleared() {
		_spec.ClearField(billingprofile.FieldImagePrice4k, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BatchImageDiscountMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBatchImageDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBatchImageDiscountMultiplier(); ok {
		_spec.AddField(billingprofile.FieldBatchImageDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BatchImageHoldMultiplier(); ok {
		_spec.SetField(billingprofile.FieldBatchImageHoldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBatchImageHoldMultiplier(); ok {
		_spec.AddField(billingprofile.FieldBatchImageHoldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.VideoRateIndependent(); ok {
		_spec.SetField(billingprofile.FieldVideoRateIndependent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VideoRateMultiplier(); ok {
		_spec.SetField(billingprofile.FieldVideoRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVideoRateMultiplier(); ok {
		_spec.AddField(billingprofile.FieldVideoRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.VideoPrice480p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice480p, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVideoPrice480p(); ok {
		_spec.AddField(billingprofile.FieldVideoPrice480p, field.TypeFloat64, value)
	}
	if _u.mutation.VideoPrice480pCleared() {
		_spec.ClearField(billingprofile.FieldVideoPrice480p, field.TypeFloat64)
	}
	if value, ok := _u.mutation.VideoPrice720p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice720p, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVideoPrice720p(); ok {
		_spec.AddField(billingprofile.FieldVideoPrice720p, field.TypeFloat64, value)
	}
	if _u.mutation.VideoPrice720pCleared() {
		_spec.ClearField(billingprofile.FieldVideoPrice720p, field.TypeFloat64)
	}
	if value, ok := _u.mutation.VideoPrice1080p(); ok {
		_spec.SetField(billingprofile.FieldVideoPrice1080p, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVideoPrice1080p(); ok {
		_spec.AddField(billingprofile.FieldVideoPrice1080p, field.TypeFloat64, value)
	}
	if _u.mutation.VideoPrice1080pCleared() {
		_spec.ClearField(billingprofile.FieldVideoPrice1080p, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WebSearchPricePerCall(); ok {
		_spec.SetField(billingprofile.FieldWebSearchPricePerCall, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWebSearchPricePerCall(); ok {
		_spec.AddField(billingprofile.FieldWebSearchPricePerCall, field.TypeFloat64, value)
	}
	if _u.mutation.WebSearchPricePerCallCleared() {
		_spec.ClearField(billingprofile.FieldWebSearchPricePerCall, field.TypeFloat64)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   billingprofile.GroupTable,
			Columns: []string{billingprofile.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   billingprofile.GroupTable,
			Columns: []string{billingprofile.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BillingProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
