// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/billingprofile"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// BillingProfile is the model entity for the BillingProfile schema.
type BillingProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// BalanceRateMultiplier holds the value of the "balance_rate_multiplier" field.
	BalanceRateMultiplier float64 `json:"balance_rate_multiplier,omitempty"`
	// PeakRateEnabled holds the value of the "peak_rate_enabled" field.
	PeakRateEnabled bool `json:"peak_rate_enabled,omitempty"`
	// PeakStart holds the value of the "peak_start" field.
	PeakStart string `json:"peak_start,omitempty"`
	// PeakEnd holds the value of the "peak_end" field.
	PeakEnd string `json:"peak_end,omitempty"`
	// PeakRateMultiplier holds the value of the "peak_rate_multiplier" field.
	PeakRateMultiplier float64 `json:"peak_rate_multiplier,omitempty"`
	// ImageRateIndependent holds the value of the "image_rate_independent" field.
	ImageRateIndependent bool `json:"image_rate_independent,omitempty"`
	// ImageRateMultiplier holds the value of the "image_rate_multiplier" field.
	ImageRateMultiplier float64 `json:"image_rate_multiplier,omitempty"`
	// ImagePrice1k holds the value of the "image_price_1k" field.
	ImagePrice1k *float64 `json:"image_price_1k,omitempty"`
	// ImagePrice2k holds the value of the "image_price_2k" field.
	ImagePrice2k *float64 `json:"image_price_2k,omitempty"`
	// ImagePrice4k holds the value of the "image_price_4k" field.
	ImagePrice4k *float64 `json:"image_price_4k,omitempty"`
	// BatchImageDiscountMultiplier holds the value of the "batch_image_discount_multiplier" field.
	BatchImageDiscountMultiplier float64 `json:"batch_image_discount_multiplier,omitempty"`
	// BatchImageHoldMultiplier holds the value of the "batch_image_hold_multiplier" field.
	BatchImageHoldMultiplier float64 `json:"batch_image_hold_multiplier,omitempty"`
	// VideoRateIndependent holds the value of the "video_rate_independent" field.
	VideoRateIndependent bool `json:"video_rate_independent,omitempty"`
	// VideoRateMultiplier holds the value of the "video_rate_multiplier" field.
	VideoRateMultiplier float64 `json:"video_rate_multiplier,omitempty"`
	// VideoPrice480p holds the value of the "video_price_480p" field.
	VideoPrice480p *float64 `json:"video_price_480p,omitempty"`
	// VideoPrice720p holds the value of the "video_price_720p" field.
	VideoPrice720p *float64 `json:"video_price_720p,omitempty"`
	// VideoPrice1080p holds the value of the "video_price_1080p" field.
	VideoPrice1080p *float64 `json:"video_price_1080p,omitempty"`
	// WebSearchPricePerCall holds the value of the "web_search_price_per_call" field.
	WebSearchPricePerCall *float64 `json:"web_search_price_per_call,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillingProfileQuery when eager-loading is set.
	Edges        BillingProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BillingProfileEdges holds the relations/edges for other nodes in the graph.
type BillingProfileEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillingProfileEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillingProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billingprofile.FieldPeakRateEnabled, billingprofile.FieldImageRateIndependent, billingprofile.FieldVideoRateIndependent:
			values[i] = new(sql.NullBool)
		case billingprofile.FieldBalanceRateMultiplier, billingprofile.FieldPeakRateMultiplier, billingprofile.FieldImageRateMultiplier, billingprofile.FieldImagePrice1k, billingprofile.FieldImagePrice2k, billingprofile.FieldImagePrice4k, billingprofile.FieldBatchImageDiscountMultiplier, billingprofile.FieldBatchImageHoldMultiplier, billingprofile.FieldVideoRateMultiplier, billingprofile.FieldVideoPrice480p, billingprofile.FieldVideoPrice720p, billingprofile.FieldVideoPrice1080p, billingprofile.FieldWebSearchPricePerCall:
			values[i] = new(sql.NullFloat64)
		case billingprofile.FieldID, billingprofile.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case billingprofile.FieldPeakStart, billingprofile.FieldPeakEnd:
			values[i] = new(sql.NullString)
		case billingprofile.FieldCreatedAt, billingprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillingProfile fields.
func (_m *BillingProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billingprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case billingprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case billingprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case billingprofile.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case billingprofile.FieldBalanceRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_rate_multiplier", values[i])
			} else if value.Valid {
				_m.BalanceRateMultiplier = value.Float64
			}
		case billingprofile.FieldPeakRateEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field peak_rate_enabled", values[i])
			} else if value.Valid {
				_m.PeakRateEnabled = value.Bool
			}
		case billingprofile.FieldPeakStart:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field peak_start", values[i])
			} else if value.Valid {
				_m.PeakStart = value.String
			}
		case billingprofile.FieldPeakEnd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field peak_end", values[i])
			} else if value.Valid {
				_m.PeakEnd = value.String
			}
		case billingprofile.FieldPeakRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field peak_rate_multiplier", values[i])
			} else if value.Valid {
				_m.PeakRateMultiplier = value.Float64
			}
		case billingprofile.FieldImageRateIndependent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field image_rate_independent", values[i])
			} else if value.Valid {
				_m.ImageRateIndependent = value.Bool
			}
		case billingprofile.FieldImageRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_rate_multiplier", values[i])
			} else if value.Valid {
				_m.ImageRateMultiplier = value.Float64
			}
		case billingprofile.FieldImagePrice1k:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_price_1k", values[i])
			} else if value.Valid {
				_m.ImagePrice1k = new(float64)
				*_m.ImagePrice1k = value.Float64
			}
		case billingprofile.FieldImagePrice2k:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_price_2k", values[i])
			} else if value.Valid {
				_m.ImagePrice2k = new(float64)
				*_m.ImagePrice2k = value.Float64
			}
		case billingprofile.FieldImagePrice4k:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_price_4k", values[i])
			} else if value.Valid {
				_m.ImagePrice4k = new(float64)
				*_m.ImagePrice4k = value.Float64
			}
		case billingprofile.FieldBatchImageDiscountMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_image_discount_multiplier", values[i])
			} else if value.Valid {
				_m.BatchImageDiscountMultiplier = value.Float64
			}
		case billingprofile.FieldBatchImageHoldMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_image_hold_multiplier", values[i])
			} else if value.Valid {
				_m.BatchImageHoldMultiplier = value.Float64
			}
		case billingprofile.FieldVideoRateIndependent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field video_rate_independent", values[i])
			} else if value.Valid {
				_m.VideoRateIndependent = value.Bool
			}
		case billingprofile.FieldVideoRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field video_rate_multiplier", values[i])
			} else if value.Valid {
				_m.VideoRateMultiplier = value.Float64
			}
		case billingprofile.FieldVideoPrice480p:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field video_price_480p", values[i])
			} else if value.Valid {
				_m.VideoPrice480p = new(float64)
				*_m.VideoPrice480p = value.Float64
			}
		case billingprofile.FieldVideoPrice720p:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field video_price_720p", values[i])
			} else if value.Valid {
				_m.VideoPrice720p = new(float64)
				*_m.VideoPrice720p = value.Float64
			}
		case billingprofile.FieldVideoPrice1080p:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field video_price_1080p", values[i])
			} else if value.Valid {
				_m.VideoPrice1080p = new(float64)
				*_m.VideoPrice1080p = value.Float64
			}
		case billingprofile.FieldWebSearchPricePerCall:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field web_search_price_per_call", values[i])
			} else if value.Valid {
				_m.WebSearchPricePerCall = new(float64)
				*_m.WebSearchPricePerCall = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillingProfile.
// This includes values selected through modifiers, order, etc.
func (_m *BillingProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the BillingProfile entity.
func (_m *BillingProfile) QueryGroup() *GroupQuery {
	return NewBillingProfileClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this BillingProfile.
// Note that you need to call BillingProfile.Unwrap() before calling this method if this BillingProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BillingProfile) Update() *BillingProfileUpdateOne {
	return NewBillingProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BillingProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BillingProfile) Unwrap() *BillingProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BillingProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BillingProfile) String() string {
	var builder strings.Builder
	builder.WriteString("BillingProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("balance_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("peak_rate_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeakRateEnabled))
	builder.WriteString(", ")
	builder.WriteString("peak_start=")
	builder.WriteString(_m.PeakStart)
	builder.WriteString(", ")
	builder.WriteString("peak_end=")
	builder.WriteString(_m.PeakEnd)
	builder.WriteString(", ")
	builder.WriteString("peak_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeakRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("image_rate_independent=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageRateIndependent))
	builder.WriteString(", ")
	builder.WriteString("image_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageRateMultiplier))
	builder.WriteString(", ")
	if v := _m.ImagePrice1k; v != nil {
		builder.WriteString("image_price_1k=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImagePrice2k; v != nil {
		builder.WriteString("image_price_2k=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImagePrice4k; v != nil {
		builder.WriteString("image_price_4k=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("batch_image_discount_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchImageDiscountMultiplier))
	builder.WriteString(", ")
	builder.WriteString("batch_image_hold_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchImageHoldMultiplier))
	builder.WriteString(", ")
	builder.WriteString("video_rate_independent=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoRateIndependent))
	builder.WriteString(", ")
	builder.WriteString("video_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoRateMultiplier))
	builder.WriteString(", ")
	if v := _m.VideoPrice480p; v != nil {
		builder.WriteString("video_price_480p=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.VideoPrice720p; v != nil {
		builder.WriteString("video_price_720p=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.VideoPrice1080p; v != nil {
		builder.WriteString("video_price_1080p=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WebSearchPricePerCall; v != nil {
		builder.WriteString("web_search_price_per_call=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BillingProfiles is a parsable slice of BillingProfile.
type BillingProfiles []*BillingProfile
